Repository Badger-Finance/badger-api, pull requests merged in 2022-06, with the labels that each got.

#1226 Revert "chore: deprecate digg"
  src/chains/config/eth.config.ts
  src/vaults/__snapshots__/vaults.controller.spec.ts.snap
Labels: enhancement

#1227 release: bvecvx processor update + swagger fix
  .gitattributes
  .github/workflows/build.yml
  .github/workflows/coverage.yml
  .github/workflows/deploy.yml
  package.json
  src/abi/balancer-vault.abi
  src/abi/ibbtc.abi
  src/abi/weighted-pool.abi
  src/chains/strategies/base.strategy.ts
  src/citadel/__snapshots__/citadel.controller.spec.ts.snap
  src/citadel/__snapshots__/citadel.utils.spec.ts.snap
  src/citadel/citadel.controller.spec.ts
  src/citadel/citadel.service.spec.ts
  src/citadel/citadel.utils.spec.ts
  src/citadel/citadel.utils.ts
  src/citadel/mocks/citadel-chart-data-blob.model.mock.ts
  src/citadel/mocks/citadel-list-rewards.sdk.mock.ts
  src/citadel/mocks/knighting-round-knight.graph.mock.ts
  src/citadel/mocks/query-citadel-data.util.mock.ts
  src/citadel/mocks/query-treasury-summary.util.mock.ts
  src/citadel/mocks/rewards-snapshot.model.mock.ts
  src/config/constants.ts
  src/config/tokens.config.ts
  src/contracts/BalancerVault.ts
  src/contracts/Ibbtc.ts
  src/contracts/WeightedPool.ts
  src/contracts/factories/BalancerVault__factory.ts
  src/contracts/factories/Ibbtc__factory.ts
  src/contracts/factories/WeightedPool__factory.ts
  src/contracts/index.ts
  src/indexers/boosts-indexer.ts
  src/indexers/price-indexer.ts
  src/prices/__snapshots__/prices.controller.spec.ts.snap
  src/prices/__snapshots__/prices.service.spec.ts.snap
  src/prices/enums/pricing-type.enum.ts
  src/protocols/strategies/balancer.strategy.ts
  src/protocols/strategies/convex.strategy.ts
  src/test/tests.utils.ts
  src/tokens/config/eth-tokens.config.ts
  src/tokens/mocks/full-token.mock.ts
  yarn.lock
Labels: bug, enhancement

#1231 chore: use dynamic address
  src/citadel/config/citadel-treasury.config.ts
Labels: enhancement

#1234 chore: intiial sdk update + knighting round rehearsal prep
  package.json
  src/citadel/citadel.constants.ts
  src/citadel/citadel.controller.spec.ts
  src/citadel/citadel.service.ts
  src/tokens/mocks/full-token.mock.ts
  src/vaults/__snapshots__/vaults.controller.spec.ts.snap
  yarn.lock
Labels: enhancement

#1235 chore: update deploy yaml
  .github/workflows/deploy.yml
  package.json
  src/citadel/__snapshots__/citadel.controller.spec.ts.snap
  src/citadel/citadel.constants.ts
  src/citadel/citadel.controller.spec.ts
  src/citadel/citadel.service.ts
  src/citadel/config/citadel-treasury.config.ts
  src/config/tokens.config.ts
  src/prices/__snapshots__/prices.controller.spec.ts.snap
  src/prices/__snapshots__/prices.service.spec.ts.snap
  src/tokens/config/eth-tokens.config.ts
  src/tokens/mocks/full-token.mock.ts
  src/vaults/__snapshots__/vaults.controller.spec.ts.snap
  yarn.lock
Labels: enhancement

#1236 chore: remove logging, reorder knights
  src/citadel/citadel.constants.ts
  src/citadel/citadel.service.ts
Labels: bug, dependencies

#1238 chore: utilize mocked sdk functions
  src/citadel/__snapshots__/citadel.controller.spec.ts.snap
  src/citadel/citadel.controller.spec.ts
  src/citadel/citadel.controller.ts
  src/citadel/citadel.service.ts
  src/citadel/citadel.utils.ts
  src/citadel/interfaces/get-list-rewards-options.interface.ts
Labels: enhancement

#1240 chore: update citadel leaderboard sorting + vote weight metrics
  src/citadel/__snapshots__/citadel.controller.spec.ts.snap
  src/citadel/citadel.service.ts
  src/citadel/citadel.utils.ts
Labels: bug

#1242 fix: update citadel tests mocks
  codegen.yml
  package.json
  src/citadel/__snapshots__/citadel.controller.spec.ts.snap
  src/citadel/citadel.controller.spec.ts
  src/citadel/citadel.service.ts
  src/citadel/citadel.utils.ts
  src/citadel/interfaces/citadel-knights-round-stat.interface.ts
  src/citadel/mocks/knighting-round-knight.graph.mock.ts
  src/graphql/fragments/vote.fragment.graphql
  src/graphql/generated/citadel.knights.round.ts
  src/graphql/queries/votes.query.graphql
  yarn.lock
Labels: test

#1243 feat: support user epoch projected earnings
  package.json
  src/aws/models/citadel-rewards-snapshot.ts
  src/citadel/__snapshots__/citadel.controller.spec.ts.snap
  src/citadel/__snapshots__/citadel.utils.spec.ts.snap
  src/citadel/citadel.controller.spec.ts
  src/citadel/citadel.service.ts
  src/citadel/citadel.utils.ts
  src/citadel/destructors/citadel-reward-event.destructor.ts
  src/citadel/interfaces/citadel-reward-event-model.interface.ts
  src/citadel/interfaces/citadel-reward-event.interface.ts
  src/indexers/citadel-rewards-indexer.ts
  yarn.lock
Labels: enhancement

#1245 chore: initial boost metrics related removals
  src/accounts/__snapshots__/accounts.utils.spec.ts.snap
  src/accounts/accounts.utils.ts
  src/aws/models/cached-account.model.ts
  src/indexers/boosts-indexer.ts
  src/indexers/indexer.utils.spec.ts
  src/indexers/leaderboard-indexer.ts
  src/test/tests.utils.ts
Labels: bug

#1246 chore: remove unused multiplier indexing
  package.json
  serverless.yml
  src/accounts/__snapshots__/accounts.controller.spec.ts.snap
  src/accounts/__snapshots__/accounts.utils.spec.ts.snap
  src/accounts/accounts.utils.spec.ts
  src/accounts/accounts.utils.ts
  src/accounts/interfaces/account-model.interface.ts
  src/aws/models/cached-account.model.ts
  src/aws/models/cached-boost.model.ts
  src/indexers/__snapshots__/boosts-indexer.spec.ts.snap
  src/indexers/boosts-indexer.spec.ts
  src/indexers/boosts-indexer.ts
  src/indexers/leaderboard-indexer.spec.ts
  src/leaderboards/leaderboards.utils.spec.ts
  src/leaderboards/leaderboards.utils.ts
  src/rewards/interfaces/cached-boost-multiplier.interface.ts
  src/test/tests.utils.ts
  yarn.lock
Labels: enhancement

#1247 chore: add try / catch + utilize block queries
  serverless.yml
  src/citadel/citadel.service.ts
Labels: bug

#1248 fix: update test mock
  src/citadel/citadel.controller.spec.ts
Labels: test

#1249 fix: utilize type checking and proper entry field
  src/indexers/leaderboard-indexer.ts
  src/test/tests.utils.ts
Labels: bug

#1250 release: citadel updates + account trimming
  codegen.yml
  package.json
  serverless.yml
  src/accounts/__snapshots__/accounts.controller.spec.ts.snap
  src/accounts/__snapshots__/accounts.utils.spec.ts.snap
  src/accounts/accounts.utils.spec.ts
  src/accounts/accounts.utils.ts
  src/accounts/interfaces/account-model.interface.ts
  src/aws/models/cached-account.model.ts
  src/aws/models/cached-boost.model.ts
  src/aws/models/citadel-rewards-snapshot.ts
  src/charts/__snapshots__/charts.utils.spec.ts.snap
  src/charts/charts.utils.spec.ts
  src/citadel/__snapshots__/citadel.controller.spec.ts.snap
  src/citadel/__snapshots__/citadel.utils.spec.ts.snap
  src/citadel/citadel.constants.ts
  src/citadel/citadel.controller.spec.ts
  src/citadel/citadel.controller.ts
  src/citadel/citadel.service.ts
  src/citadel/citadel.utils.ts
  src/citadel/destructors/citadel-reward-event.destructor.ts
  src/citadel/interfaces/citadel-knights-round-stat.interface.ts
  src/citadel/interfaces/citadel-reward-event-model.interface.ts
  src/citadel/interfaces/citadel-reward-event.interface.ts
  src/citadel/interfaces/get-list-rewards-options.interface.ts
  src/citadel/mocks/knighting-round-knight.graph.mock.ts
  src/graphql/fragments/vote.fragment.graphql
  src/graphql/generated/citadel.knights.round.ts
  src/graphql/queries/votes.query.graphql
  src/indexers/__snapshots__/boosts-indexer.spec.ts.snap
  src/indexers/boosts-indexer.spec.ts
  src/indexers/boosts-indexer.ts
  src/indexers/citadel-rewards-indexer.ts
  src/indexers/indexer.utils.spec.ts
  src/indexers/leaderboard-indexer.spec.ts
  src/indexers/leaderboard-indexer.ts
  src/leaderboards/leaderboards.utils.spec.ts
  src/leaderboards/leaderboards.utils.ts
  src/rewards/interfaces/cached-boost-multiplier.interface.ts
  src/test/tests.utils.ts
  src/vaults/vaults.utils.ts
  yarn.lock
Labels: enhancement

#1251 chore: update bvecvx performance fee
  src/vaults/vaults.utils.ts
Labels: bug

#1252 release: update bvecvx performance fees
  src/vaults/vaults.utils.ts
Labels: bug

#1253 fix: move user balance updates to account invocation
  serverless.yml
  src/accounts/__snapshots__/accounts.service.spec.ts.snap
  src/accounts/__snapshots__/accounts.utils.spec.ts.snap
  src/accounts/accounts.service.spec.ts
  src/accounts/accounts.utils.ts
  src/aws/models/cached-account.model.ts
  src/indexers/accounts-indexer.spec.ts
  src/indexers/accounts-indexer.ts
  src/indexers/indexer.utils.spec.ts
  src/indexers/indexer.utils.ts
  src/indexers/interfaces/account-index-event.interface.ts
  src/test/tests.utils.ts
Labels: bug

#1257 fix: handle bribes processor address updates
  seed/prices.json
  seed/vault-snapshots.json
  src/accounts/accounts.utils.ts
  src/protocols/strategies/convex.strategy.ts
  src/rewards/rewards.utils.ts
Labels: bug

#1259 fix: bvecvx include new bribes processor
  seed/prices.json
  seed/vault-snapshots.json
  src/accounts/accounts.utils.ts
  src/protocols/strategies/convex.strategy.ts
  src/rewards/rewards.utils.ts
Labels: bug

#1260 chore: deprecate digg vaults
  src/chains/config/eth.config.ts
  src/vaults/__snapshots__/vaults.controller.spec.ts.snap
Labels: enhancement

#1261 release: digg deprecation
  src/chains/config/eth.config.ts
  src/vaults/__snapshots__/vaults.controller.spec.ts.snap
Labels: enhancement

#1262 feat: add v3 endpoints
  package.json
  src/ControllerRegistry.ts
  src/Server.ts
  src/accounts/__snapshots__/account.v3.controller.spec.ts.snap
  src/accounts/__snapshots__/accounts.v2.controller.spec.ts.snap
  src/accounts/account.v3.controller.spec.ts
  src/accounts/account.v3.controller.ts
  src/accounts/accounts.service.ts
  src/accounts/accounts.v2.controller.spec.ts
  src/accounts/accounts.v2.controller.ts
  src/common/filters/api-exception-filter.ts
  src/common/filters/tsed-exception-filter.ts
  src/errors/allocation/nodata.for.addr.error.ts
  src/errors/allocation/nodata.for.chain.error.ts
  src/errors/allocation/nodata.for.vault.error.ts
  src/errors/allocation/not.found.error.ts
  src/errors/base.error.ts
  src/errors/enums/error.codes.enum.ts
  src/errors/enums/newtroks.status.enum.ts
  src/errors/validation/base.validation.error.ts
  src/errors/validation/invalid.addr.error.ts
  src/errors/validation/query.param.error.ts
  src/errors/validation/unsupported.chain.error.ts
  src/proofs/__snapshots__/proof.v3.controller.spec.ts.snap
  src/proofs/__snapshots__/proofs.v2.controller.spec.ts.snap
  src/proofs/proof.v3.controller.spec.ts
  src/proofs/proof.v3.controller.ts
  src/proofs/proofs.service.spec.ts
  src/proofs/proofs.service.ts
  src/proofs/proofs.v2.controller.spec.ts
  src/proofs/proofs.v2.controller.ts
  src/rewards/__snapshots__/reward.v2.controller.spec.ts.snap
  src/rewards/__snapshots__/reward.v3.controller.spec.ts.snap
  src/rewards/reward.v2.controller.spec.ts
  src/rewards/reward.v2.controller.ts
  src/rewards/reward.v3.controller.spec.ts
  src/rewards/reward.v3.controller.ts
  src/rewards/rewards.service.spec.ts
  src/rewards/rewards.service.ts
  src/rewards/rewards.v2.controller.ts
  src/test/tests.utils.ts
  src/vaults/__snapshots__/vault.v3.controller.spec.ts.snap
  src/vaults/__snapshots__/vaults.v2.controller.spec.ts.snap
  src/vaults/setts.v2.controller.ts
  src/vaults/vault.v3.controller.spec.ts
  src/vaults/vault.v3.controller.ts
  src/vaults/vaults.service.ts
  src/vaults/vaults.v2.controller.spec.ts
  src/vaults/vaults.v2.controller.ts
  yarn.lock
Labels: enhancement

#1265 feat: add graviaura
  package.json
  src/chains/config/eth.config.ts
  src/config/tokens.config.ts
  src/metrics/__snapshots__/metrics.utils.spec.ts.snap
  src/prices/__snapshots__/prices.controller.spec.ts.snap
  src/prices/__snapshots__/prices.service.spec.ts.snap
  src/protocols/strategies/balancer.strategy.ts
  src/tokens/config/eth-tokens.config.ts
  src/vaults/__snapshots__/vault.v3.controller.spec.ts.snap
  src/vaults/__snapshots__/vaults.service.spec.ts.snap
  src/vaults/__snapshots__/vaults.v2.controller.spec.ts.snap
  yarn.lock
Labels: enhancement

#1268 release: graviaura support + initial v3 api
  package.json
  src/ControllerRegistry.ts
  src/Server.ts
  src/accounts/__snapshots__/account.v3.controller.spec.ts.snap
  src/accounts/__snapshots__/accounts.v2.controller.spec.ts.snap
  src/accounts/account.v3.controller.spec.ts
  src/accounts/account.v3.controller.ts
  src/accounts/accounts.service.ts
  src/accounts/accounts.v2.controller.spec.ts
  src/accounts/accounts.v2.controller.ts
  src/chains/config/eth.config.ts
  src/common/filters/api-exception-filter.ts
  src/common/filters/tsed-exception-filter.ts
  src/config/tokens.config.ts
  src/errors/allocation/nodata.for.addr.error.ts
  src/errors/allocation/nodata.for.chain.error.ts
  src/errors/allocation/nodata.for.vault.error.ts
  src/errors/allocation/not.found.error.ts
  src/errors/base.error.ts
  src/errors/enums/error.codes.enum.ts
  src/errors/enums/newtroks.status.enum.ts
  src/errors/validation/base.validation.error.ts
  src/errors/validation/invalid.addr.error.ts
  src/errors/validation/query.param.error.ts
  src/errors/validation/unsupported.chain.error.ts
  src/metrics/__snapshots__/metrics.utils.spec.ts.snap
  src/prices/__snapshots__/prices.controller.spec.ts.snap
  src/prices/__snapshots__/prices.service.spec.ts.snap
  src/proofs/__snapshots__/proof.v3.controller.spec.ts.snap
  src/proofs/__snapshots__/proofs.v2.controller.spec.ts.snap
  src/proofs/proof.v3.controller.spec.ts
  src/proofs/proof.v3.controller.ts
  src/proofs/proofs.service.spec.ts
  src/proofs/proofs.service.ts
  src/proofs/proofs.v2.controller.spec.ts
  src/proofs/proofs.v2.controller.ts
  src/protocols/strategies/balancer.strategy.ts
  src/rewards/__snapshots__/reward.v2.controller.spec.ts.snap
  src/rewards/__snapshots__/reward.v3.controller.spec.ts.snap
  src/rewards/reward.v2.controller.spec.ts
  src/rewards/reward.v2.controller.ts
  src/rewards/reward.v3.controller.spec.ts
  src/rewards/reward.v3.controller.ts
  src/rewards/rewards.service.spec.ts
  src/rewards/rewards.service.ts
  src/rewards/rewards.v2.controller.ts
  src/test/tests.utils.ts
  src/tokens/config/eth-tokens.config.ts
  src/vaults/__snapshots__/vault.v3.controller.spec.ts.snap
  src/vaults/__snapshots__/vaults.service.spec.ts.snap
  src/vaults/__snapshots__/vaults.v2.controller.spec.ts.snap
  src/vaults/setts.v2.controller.ts
  src/vaults/vault.v3.controller.spec.ts
  src/vaults/vault.v3.controller.ts
  src/vaults/vaults.service.ts
  src/vaults/vaults.v2.controller.spec.ts
  src/vaults/vaults.v2.controller.ts
  yarn.lock
Labels: enhancement

#1269 chore: update routes + tests
  src/ControllerRegistry.ts
  src/rewards/__snapshots__/rewards.v3.controller.spec.ts.snap
  src/rewards/rewards.v3.controller.spec.ts
  src/rewards/rewards.v3.controller.ts
Labels: bug

#1271 chore: update harvest forwarder to use 30 days info and cleanup comments
  src/protocols/strategies/convex.strategy.ts
Labels: bug

#1277 fix: leaderboard improper boost updating
  .github/workflows/deploy.yml
  package.json
  src/accounts/accounts.utils.spec.ts
  src/accounts/accounts.utils.ts
  src/aws/models/cached-boost.model.ts
  src/indexers/accounts-indexer.ts
  src/indexers/leaderboard-indexer.spec.ts
  src/indexers/leaderboard-indexer.ts
  src/indexers/vault-snapshots-indexer.ts
  src/leaderboards/__snapshots__/leaderboards.utils.spec.ts.snap
  src/leaderboards/leaderboards.utils.spec.ts
  src/leaderboards/leaderboards.utils.ts
  src/test/tests.utils.ts
  src/vaults/vaults.utils.spec.ts
  yarn.lock
Labels: bug

#1280 fix: revert tests node version
  .github/workflows/coverage.yml
  .github/workflows/deploy.yml
Labels: bug

#1281 fix: utilize checksum addr
  src/rewards/rewards.service.ts
Labels: bug

#1284 chore: add vault timestamp specific queries
  src/ControllerRegistry.ts
  src/tokens/destructors/token.destructor.ts
  src/vaults/__snapshots__/vaults.v3.controller.spec.ts.snap
  src/vaults/enums/harvest.enum.ts
  src/vaults/vaults.service.ts
  src/vaults/vaults.utils.ts
  src/vaults/vaults.v3.controller.spec.ts
  src/vaults/vaults.v3.controller.ts
Labels: enhancement

#1287 fix: utilize requested timestamps
  src/prices/prices.utils.ts
  src/vaults/vaults.utils.ts
Labels: bug

#1291 feat: add balancer pool lp token resolution
  src/chains/config/eth.config.ts
  src/chains/strategies/base.strategy.ts
  src/config/tokens.config.ts
  src/metrics/__snapshots__/metrics.utils.spec.ts.snap
  src/prices/__snapshots__/prices.controller.spec.ts.snap
  src/prices/__snapshots__/prices.service.spec.ts.snap
  src/protocols/strategies/balancer.strategy.ts
  src/tokens/config/eth-tokens.config.ts
  src/tokens/interfaces/token-config.interface.ts
  src/vaults/__snapshots__/vaults.service.spec.ts.snap
  src/vaults/__snapshots__/vaults.v2.controller.spec.ts.snap
  src/vaults/__snapshots__/vaults.v3.controller.spec.ts.snap
Labels: enhancement

#1293 fix: utilize stable swap derivation
  seed/prices.json
  src/abi/stable-pool.abi
  src/config/tokens.config.ts
  src/contracts/StablePool.ts
  src/contracts/factories/StablePool__factory.ts
  src/contracts/index.ts
  src/prices/__snapshots__/prices.controller.spec.ts.snap
  src/prices/__snapshots__/prices.service.spec.ts.snap
  src/protocols/strategies/balancer.strategy.ts
  src/tokens/config/eth-tokens.config.ts
Labels: enhancement

#1299 release: apr start block utilization
  package.json
  src/protocols/strategies/convex.strategy.ts
  src/vaults/vaults.utils.ts
  yarn.lock
Labels: bug

#1300 chore: remove bribes processors references
  .eslintrc.js
  package.json
  seed/prices.json
  seed/token-info.json
  seed/vault-snapshots.json
  src/accounts/accounts.utils.spec.ts
  src/accounts/accounts.utils.ts
  src/aws/types/convertable-data-blob.ts
  src/citadel/citadel.service.ts
  src/citadel/destructors/citadel-data.destructor.ts
  src/protocols/strategies/convex.strategy.ts
  src/test/tests.utils.ts
  src/vaults/vaults.utils.ts
  yarn.lock
Labels: bug
