Repository Badger-Finance/badger-api, pull requests merged in 2022-09, with the labels that each got.

#1506 feat: add vault harvest block persistence
  src/aws/models/vault-definition.model.ts
  src/indexers/vault-harvests-indexer.spec.ts
  src/indexers/vault-harvests-indexer.ts
  src/test/constants.ts
  src/vaults/harvests.utils.spec.ts
  src/vaults/harvests.utils.ts
Labels: bug, enhancement

#1507 fix: always update a complete vault indexed block
  src/indexers/vault-harvests-indexer.ts
Labels: bug

#1508 fix: do not revert indexed block
  src/indexers/__snapshots__/indexer.utils.spec.ts.snap
  src/indexers/indexer.utils.ts
  src/indexers/vault-harvests-indexer.spec.ts
Labels: bug

#1509 refactor: update persistence logic
  src/indexers/vault-harvests-indexer.ts
  src/vaults/harvests.utils.ts
Labels: bug

#1510 refactor: bvecvx vault logic
  serverless.yml
  src/indexers/vault-harvests-indexer.ts
  src/vaults/harvests.utils.ts
  src/vaults/influence.utils.ts
Labels: bug

#1511 fix: update vault harvest query
  src/vaults/harvests.utils.ts
Labels: bug

#1513 feat: support gross vault performances
  package.json
  serverless.yml
  src/accounts/accounts.utils.spec.ts
  src/aws/models/cached-yield-source.interface.ts
  src/aws/models/current-vault-snapshot.model.ts
  src/aws/models/vault-token-balance.model.ts
  src/aws/models/vault-yield-event.model.ts
  src/aws/models/yield-source.model.ts
  src/aws/models/yield-summary.model.ts
  src/indexers/__snapshots__/indexer.utils.spec.ts.snap
  src/indexers/apy-snapshots-indexer.spec.ts
  src/indexers/apy-snapshots-indexer.ts
  src/indexers/indexer.utils.ts
  src/indexers/vault-balances-indexer.spec.ts
  src/indexers/vault-snapshots-indexer.ts
  src/indexers/yield-estimates-indexer.ts
  src/metrics/__snapshots__/metrics.utils.spec.ts.snap
  src/metrics/metrics.utils.spec.ts
  src/metrics/metrics.utils.ts
  src/protocols/strategies/__snapshots__/uniswap.strategy.spec.ts.snap
  src/protocols/strategies/balancer.strategy.ts
  src/protocols/strategies/convex.strategy.ts
  src/protocols/strategies/oxdao.strategy.ts
  src/protocols/strategies/strategy.utils.ts
  src/protocols/strategies/sushiswap.strategy.ts
  src/protocols/strategies/swapr.strategy.ts
  src/protocols/strategies/uniswap.strategy.spec.ts
  src/protocols/strategies/uniswap.strategy.ts
  src/rewards/rewards.utils.ts
  src/test/constants.ts
  src/tokens/tokens.utils.spec.ts
  src/tokens/tokens.utils.ts
  src/vaults/__snapshots__/harvests.utils.spec.ts.snap
  src/vaults/__snapshots__/vaults.service.spec.ts.snap
  src/vaults/__snapshots__/vaults.utils.spec.ts.snap
  src/vaults/__snapshots__/vaults.v2.controller.spec.ts.snap
  src/vaults/__snapshots__/vaults.v3.controller.spec.ts.snap
  src/vaults/__snapshots__/yields.utils.spec.ts.snap
  src/vaults/harvests.utils.spec.ts
  src/vaults/harvests.utils.ts
  src/vaults/influence.utils.ts
  src/vaults/interfaces/vault-model.interface.ts
  src/vaults/interfaces/yield-event.ts
  src/vaults/interfaces/yield-sources.interface.ts
  src/vaults/vaults.service.spec.ts
  src/vaults/vaults.service.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
  src/vaults/vaults.v2.controller.spec.ts
  src/vaults/vaults.v2.controller.ts
  src/vaults/vaults.v3.controller.ts
  src/vaults/yields.utils.ts
  yarn.lock
Labels: enhancement

#1514 refactor: temp table rename for deploy
  serverless.yml
Labels: bug

#1516 fix: update vault balances indexer
  src/indexers/vault-balances-indexer.ts
  src/protocols/strategies/__snapshots__/uniswap.strategy.spec.ts.snap
  src/protocols/strategies/balancer.strategy.ts
  src/protocols/strategies/convex.strategy.ts
  src/protocols/strategies/uniswap.strategy.ts
  src/vaults/vaults.service.ts
Labels: bug

#1515 feat: add vault yield event txs, fix seed for vault snapshot
  package.json
  seed/vault-snapshots.json
  src/aws/models/vault-yield-event.model.ts
  src/test/constants.ts
  src/vaults/__snapshots__/harvests.utils.spec.ts.snap
  src/vaults/harvests.utils.ts
  src/vaults/interfaces/vault-harvests-model.interface.ts
  src/vaults/interfaces/yield-event.ts
  src/vaults/mocks/vault-harvests-on-chain.ts
  src/vaults/mocks/vaults-harvests-map.mock.ts
  src/vaults/vaults.service.ts
  src/vaults/yields.utils.ts
  yarn.lock
Labels: enhancement

#1517 chore: update v3 harvests response model
  src/vaults/vaults.v3.controller.spec.ts
  src/vaults/vaults.v3.controller.ts
Labels: enhancement

#1520 refactor: per vault start blocks
  package.json
  src/accounts/accounts.utils.spec.ts
  src/aws/models/vault-definition.model.ts
  src/contracts/BalancerVault.ts
  src/contracts/CurveBaseRegistry.ts
  src/contracts/CurvePool.ts
  src/contracts/CurvePool3.ts
  src/contracts/CurveRegistry.ts
  src/contracts/CvxLocker.ts
  src/contracts/Imbtc.ts
  src/contracts/Mhbtc.ts
  src/contracts/MstableVault.ts
  src/contracts/SolidlyPair.ts
  src/contracts/StablePhantomVault.ts
  src/contracts/StablePool.ts
  src/contracts/SwaprStaking.ts
  src/contracts/SwaprStrategy.ts
  src/contracts/UniV2.ts
  src/contracts/WeightedPool.ts
  src/contracts/common.ts
  src/contracts/factories/BalancerVault__factory.ts
  src/contracts/factories/CurveBaseRegistry__factory.ts
  src/contracts/factories/CurvePool3__factory.ts
  src/contracts/factories/CurvePool__factory.ts
  src/contracts/factories/CurveRegistry__factory.ts
  src/contracts/factories/CvxLocker__factory.ts
  src/contracts/factories/Imbtc__factory.ts
  src/contracts/factories/Mhbtc__factory.ts
  src/contracts/factories/MstableVault__factory.ts
  src/contracts/factories/SolidlyPair__factory.ts
  src/contracts/factories/StablePhantomVault__factory.ts
  src/contracts/factories/StablePool__factory.ts
  src/contracts/factories/SwaprStaking__factory.ts
  src/contracts/factories/SwaprStrategy__factory.ts
  src/contracts/factories/UniV2__factory.ts
  src/contracts/factories/WeightedPool__factory.ts
  src/contracts/factories/index.ts
  src/contracts/index.ts
  src/indexers/__snapshots__/indexer.utils.spec.ts.snap
  src/indexers/indexer.utils.spec.ts
  src/indexers/indexer.utils.ts
  yarn.lock
Labels: enhancement

#1521 fix: harvests snapshots, no undefined in txs field
  package.json
  src/indexers/vault-harvests-indexer.spec.ts
  src/test/constants.ts
  src/vaults/__snapshots__/harvests.utils.spec.ts.snap
  src/vaults/harvests.utils.spec.ts
  yarn.lock
Labels: test

#1522 refactor: continue indexing tuning
  src/indexers/vault-harvests-indexer.ts
  src/vaults/harvests.utils.ts
Labels: enhancement

#1523 refactor: utilize gross apr
  src/vaults/__snapshots__/yields.utils.spec.ts.snap
  src/vaults/interfaces/yield-sources.interface.ts
  src/vaults/vaults.service.ts
  src/vaults/yields.utils.ts
Labels: enhancement

#1524 fix: accomodate gross apr
  src/protocols/strategies/convex.strategy.ts
  src/protocols/strategies/oxdao.strategy.ts
  src/rewards/rewards.utils.ts
  src/vaults/__snapshots__/vaults.utils.spec.ts.snap
  src/vaults/__snapshots__/yields.utils.spec.ts.snap
  src/vaults/interfaces/vault-yield-evaluation.interface.ts
  src/vaults/types/vault-emission-data.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/yields.utils.spec.ts
  src/vaults/yields.utils.ts
Labels: enhancement

#1525 fix: support old cvx locker
  src/protocols/strategies/convex.strategy.ts
  src/vaults/influence.utils.ts
  src/vaults/yields.utils.ts
Labels: bug, enhancement

#1526 chore: increase scan + scan rate
  serverless.yml
  src/vaults/__snapshots__/harvests.utils.spec.ts.snap
  src/vaults/harvests.utils.spec.ts
  src/vaults/harvests.utils.ts
Labels: enhancement

#1527 chore: continue update tuning
  serverless.yml
  src/indexers/vault-harvests-indexer.ts
  src/vaults/harvests.utils.ts
Labels: enhancement

#1528 refactor: long running index
  serverless.yml
  src/vaults/harvests.utils.ts
Labels: bug

#1530 fix: add missing badger patch
  jest.config.ts
  src/patches/graviaura-badger.ts
  src/vaults/__snapshots__/yields.utils.spec.ts.snap
  src/vaults/yields.utils.ts
Labels: enhancement

#1529 fix: use fallback balance
  src/vaults/influence.utils.ts
Labels: bug

#1531 fix: initial duration inclusion
  package.json
  serverless.yml
  src/aws/models/vault-yield-event.model.ts
  src/chains/config/chain.config.ts
  src/contracts/EmissionControl.ts
  src/contracts/factories/EmissionControl__factory.ts
  src/indexers/__snapshots__/indexer.utils.spec.ts.snap
  src/indexers/indexer.utils.ts
  src/indexers/vault-definition-indexer.spec.ts
  src/indexers/vault-harvests-indexer.ts
  src/patches/graviaura-badger.ts
  src/protocols/strategies/convex.strategy.ts
  src/test/constants.ts
  src/vaults/__snapshots__/harvests.utils.spec.ts.snap
  src/vaults/__snapshots__/yields.utils.spec.ts.snap
  src/vaults/harvests.utils.spec.ts
  src/vaults/harvests.utils.ts
  src/vaults/interfaces/vault-harvests-model-v3.interface.ts
  src/vaults/interfaces/vault-yield-evaluation.interface.ts
  src/vaults/types/vault-emission-data.ts
  src/vaults/vaults.utils.ts
  src/vaults/yields.utils.spec.ts
  src/vaults/yields.utils.ts
  yarn.lock
Labels: bug

#1534 fix: initial vault persistence changes
  package.json
  seed/scripts/update-snapshots.ts
  src/aws/models/cached-yield-projection.model.ts
  src/aws/models/historic-vault-snapshot.model.ts
  src/aws/models/yield-estimate.model.ts
  src/charts/__snapshots__/charts.controller.spec.ts.snap
  src/charts/__snapshots__/charts.service.spec.ts.snap
  src/config/config.utils.ts
  src/indexers/__snapshots__/indexer.utils.spec.ts.snap
  src/indexers/indexer.utils.ts
  src/indexers/vault-harvests-indexer.ts
  src/indexers/yield-estimates-indexer.ts
  src/test/constants.ts
  src/test/mocks.utils/mock.api.chain.ts
  src/test/mocks.utils/mock.helpers.ts
  src/vaults/__snapshots__/vaults.v3.controller.spec.ts.snap
  src/vaults/__snapshots__/yields.utils.spec.ts.snap
  src/vaults/interfaces/yield-sources.interface.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
  src/vaults/yields.utils.spec.ts
  src/vaults/yields.utils.ts
  yarn.lock
Labels: bug, enhancement

#1535 release: v3 persistence fixes
  package.json
  seed/scripts/update-snapshots.ts
  src/aws/models/cached-yield-projection.model.ts
  src/aws/models/historic-vault-snapshot.model.ts
  src/aws/models/yield-estimate.model.ts
  src/charts/__snapshots__/charts.controller.spec.ts.snap
  src/charts/__snapshots__/charts.service.spec.ts.snap
  src/config/config.utils.ts
  src/indexers/__snapshots__/indexer.utils.spec.ts.snap
  src/indexers/indexer.utils.ts
  src/indexers/vault-harvests-indexer.ts
  src/indexers/yield-estimates-indexer.ts
  src/test/constants.ts
  src/test/mocks.utils/mock.api.chain.ts
  src/test/mocks.utils/mock.helpers.ts
  src/vaults/__snapshots__/vaults.v3.controller.spec.ts.snap
  src/vaults/__snapshots__/yields.utils.spec.ts.snap
  src/vaults/interfaces/yield-sources.interface.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
  src/vaults/yields.utils.spec.ts
  src/vaults/yields.utils.ts
  yarn.lock
Labels: bug, enhancement

#1536 refactor: properly handle discontinued vaults, adjust duration measure
  serverless.yml
  src/indexers/indexer.utils.ts
  src/indexers/vault-harvests-indexer.ts
  src/vaults/harvests.utils.ts
  src/vaults/yields.utils.ts
Labels: bug, enhancement

#1537 release: yield calculation remediations
  serverless.yml
  src/indexers/indexer.utils.ts
  src/indexers/vault-harvests-indexer.ts
  src/vaults/harvests.utils.ts
  src/vaults/yields.utils.ts
Labels: bug

#1541 feat: allow dev queries
  src/chains/vaults/chain.vaults.ts
Labels: enhancement

#1543 fix: update query inputs
  src/vaults/harvests.utils.ts
Labels: bug

#1544 fix: update indexer timestamp logics
  src/indexers/__snapshots__/indexer.utils.spec.ts.snap
  src/indexers/indexer.utils.ts
  src/indexers/vault-definition-indexer.spec.ts
  src/indexers/vault-definition-indexer.ts
  src/vaults/__snapshots__/harvests.utils.spec.ts.snap
  src/vaults/harvests.utils.ts
  src/vaults/yields.utils.ts
Labels: bug

#1545 fix: harvests indexer time fixes
  package.json
  src/chains/vaults/chain.vaults.ts
  src/charts/__snapshots__/charts.controller.spec.ts.snap
  src/charts/__snapshots__/charts.service.spec.ts.snap
  src/charts/charts.controller.spec.ts
  src/dev/dev.utils.ts
  src/indexers/__snapshots__/indexer.utils.spec.ts.snap
  src/indexers/indexer.utils.spec.ts
  src/indexers/indexer.utils.ts
  src/indexers/vault-definition-indexer.spec.ts
  src/indexers/vault-definition-indexer.ts
  src/metrics/__snapshots__/metrics.utils.spec.ts.snap
  src/protocols/strategies/__snapshots__/uniswap.strategy.spec.ts.snap
  src/vaults/__snapshots__/harvests.utils.spec.ts.snap
  src/vaults/__snapshots__/vaults.service.spec.ts.snap
  src/vaults/__snapshots__/vaults.v2.controller.spec.ts.snap
  src/vaults/__snapshots__/vaults.v3.controller.spec.ts.snap
  src/vaults/harvests.utils.ts
  src/vaults/yields.utils.ts
  yarn.lock
Labels: bug

#1546 chore: add eths prices
  src/config/tokens.config.ts
  src/tokens/config/eth-tokens.config.ts
Labels: enhancement

#1547 chore: add lp + vault pricing
  src/config/tokens.config.ts
  src/tokens/config/eth-tokens.config.ts
Labels: enhancement

#1551 release: reth + wsteth vaults support
  src/config/tokens.config.ts
  src/tokens/config/eth-tokens.config.ts
Labels: enhancement

#1552 fix: force update vaults def
  src/indexers/vault-definition-indexer.ts
Labels: bug

#1554 fix: filter vaults + update sdk
  package.json
  src/indexers/vault-definition-indexer.ts
  yarn.lock
Labels: enhancement

#1555 fix: sdk upgrade - vault status fix for developer vaults
  package.json
  src/indexers/vault-definition-indexer.ts
  yarn.lock
Labels: bug

#1550 fix: patch to refetch relevant data for historic vaults values in charts
  src/patches/vault-historic-data-refetch.ts
Labels: bug, enhancement

#1553 fix: clean up few unused + misnamed folder and file
  jest.config.ts
  src/aws/models/cached-leaderboard-summary.model.ts
  src/leaderboards/interfaces/leaderboard-data-model.interrface.ts
  src/leaderboards/interfaces/leaderboard-rank-summary.interface.ts
  src/vaults/destructors/boost.destructor.ts
  src/vaults/mocks/vaults-graph-sdk-map.mock.ts
  src/vaults/mocks/vaults-harvests-sdk.mock.ts
Labels: enhancement

#1557 fix: apr missing field mappings
  jest.config.ts
  src/aws/models/cached-leaderboard-summary.model.ts
  src/aws/models/cached-token-rate.interface.ts
  src/leaderboards/interfaces/leaderboard-data-model.interrface.ts
  src/leaderboards/interfaces/leaderboard-rank-summary.interface.ts
  src/patches/vault-historic-data-refetch.ts
  src/vaults/destructors/boost.destructor.ts
  src/vaults/mocks/vaults-graph-sdk-map.mock.ts
  src/vaults/mocks/vaults-harvests-sdk.mock.ts
Labels: bug

#1558 chore: abi cleanup + tsconfig tweak
  jest.config.ts
  src/abi/imbtc.abi
  src/abi/mhbtc.abi
  src/abi/mstable-vault.abi
  src/abi/swapr-staking.abi
  src/abi/swapr-strategy.abi
  src/contracts/Imbtc.ts
  src/contracts/Mhbtc.ts
  src/contracts/MstableVault.ts
  src/contracts/SwaprStaking.ts
  src/contracts/SwaprStrategy.ts
  src/contracts/factories/Imbtc__factory.ts
  src/contracts/factories/Mhbtc__factory.ts
  src/contracts/factories/MstableVault__factory.ts
  src/contracts/factories/SwaprStaking__factory.ts
  src/contracts/factories/SwaprStrategy__factory.ts
  src/contracts/factories/index.ts
  src/contracts/index.ts
  src/protocols/interfaces/pair-day-data-query.interface.ts
  src/protocols/interfaces/uni-pair-day-data.interface.ts
  src/protocols/interfaces/xsushi-apr.interface.ts
  src/protocols/strategies/oxdao.strategy.ts
  src/protocols/strategies/strategy.utils.ts
  src/protocols/strategies/sushiswap.strategy.ts
  src/protocols/strategies/swapr.strategy.ts
  src/protocols/strategies/uniswap.strategy.ts
  src/rewards/rewards.utils.ts
  tsconfig.json
Labels: enhancement

#1559 refactor: relocate file queries, typecheck model assignments
  src/accounts/accounts.utils.spec.ts
  src/accounts/accounts.utils.ts
  src/aws/models/claimable-balance.model.ts
  src/aws/models/user-claim-metadata.model.ts
  src/aws/models/user-claim-snapshot.model.ts
  src/aws/s3.utils.ts
  src/chains/config/arbitrum.config.ts
  src/chains/config/bsc.config.ts
  src/chains/config/chain.config.ts
  src/chains/config/eth.config.ts
  src/chains/config/fantom.config.ts
  src/chains/config/optimism.config.ts
  src/chains/config/polygon.config.ts
  src/chains/config/test.config.ts
  src/chains/strategies/base.strategy.ts
  src/chains/strategies/chain.strategy.ts
  src/chains/strategies/test.strategy.ts
  src/indexers/accounts-indexer.spec.ts
  src/indexers/accounts-indexer.ts
  src/indexers/leaderboard-indexer.spec.ts
  src/indexers/leaderboard-indexer.ts
  src/indexers/prices-indexer.ts
  src/prices/prices.controller.spec.ts
  src/prices/prices.utils.spec.ts
  src/prices/prices.utils.ts
  src/proofs/__snapshots__/proofs.service.spec.ts.snap
  src/proofs/proofs.service.spec.ts
  src/proofs/proofs.service.ts
  src/proofs/proofs.v2.controller.spec.ts
  src/proofs/proofs.v2.controller.ts
  src/proofs/proofs.v3.controller.spec.ts
  src/proofs/proofs.v3.controller.ts
  src/protocols/strategies/sushiswap.strategy.ts
  src/protocols/strategies/uniswap.strategy.ts
  src/rewards/reward.v2.controller.ts
  src/rewards/rewards.service.spec.ts
  src/rewards/rewards.service.ts
  src/rewards/rewards.utils.spec.ts
  src/rewards/rewards.utils.ts
  src/rewards/rewards.v2.controller.ts
  src/rewards/rewards.v3.controller.ts
  src/test/interfaces/mock-options.interface.ts
  src/test/mocks.utils/mock.api.chain.ts
  src/test/mocks.utils/mock.helpers.ts
  src/vaults/harvests.utils.spec.ts
  src/vaults/vaults.utils.spec.ts
Labels: test

#1561 test: initial influence utils test coverage
  src/test/constants.ts
  src/vaults/influence.utils.spec.ts
Labels: test

#1563 chore: improve error log
  src/indexers/yield-estimates-indexer.ts
  src/tokens/tokens.utils.ts
Labels: bug

#1562 chore: update sdk version + minor charts refactor
  package.json
  src/aws/models/chart-data-blob.model.ts
  src/aws/models/historic-vault-snapshot.model.ts
  src/aws/s3.utils.ts
  src/charts/chart-data.model.ts
  src/charts/charts.utils.spec.ts
  src/charts/charts.utils.ts
  src/charts/interfaces/chart-data.ts
  src/proofs/__snapshots__/proofs.v3.controller.spec.ts.snap
  src/proofs/proofs.v3.controller.spec.ts
  src/test/constants.ts
  src/vaults/__snapshots__/harvests.utils.spec.ts.snap
  src/vaults/harvests.utils.spec.ts
  src/vaults/harvests.utils.ts
  src/vaults/influence.utils.ts
  yarn.lock
Labels: test

#1566 fix: accomodate no balance token difference
  src/tokens/tokens.utils.ts
Labels: enhancement

#1564 fix: remove granular yield estimation
  src/indexers/indexer.utils.ts
  src/indexers/yield-estimates-indexer.ts
  src/tokens/tokens.utils.spec.ts
  src/tokens/tokens.utils.ts
  src/vaults/__snapshots__/yields.utils.spec.ts.snap
  src/vaults/yields.utils.ts
Labels: bug

#1567 feat: retry wrapper for io, inhance strategyInfo getter with it, tests
  src/indexers/indexer.utils.ts
  src/patches/vault-historic-data-refetch.ts
  src/utils/retry.utils.spec.ts
  src/utils/retry.utils.ts
  src/vaults/harvests.utils.spec.ts
  src/vaults/harvests.utils.ts
  src/vaults/vaults.utils.ts
Labels: enhancement

#1568 feat: wrap indexers IO in retry function
  serverless.yml
  src/indexers/accounts-indexer.ts
  src/indexers/apy-snapshots-indexer.ts
  src/indexers/prices-indexer.ts
  src/indexers/protocol-metric-indexer.ts
  src/indexers/vault-balances-indexer.ts
  src/indexers/vault-definition-indexer.ts
  src/indexers/vault-harvests-indexer.ts
  src/indexers/vault-snapshots-indexer.ts
  src/indexers/yield-estimates-indexer.ts
  src/utils/retry.utils.ts
Labels: enhancement

#1569 fix: update tests, remove duplicate convert
  src/prices/__snapshots__/prices.service.spec.ts.snap
  src/prices/prices.service.spec.ts
  src/prices/prices.service.ts
  src/prices/prices.utils.spec.ts
  src/prices/prices.utils.ts
  src/test/mocks.utils/mock.api.chain.ts
  src/tokens/config/arbitrum-tokens.config.ts
  src/tokens/config/bsc-tokens.config.ts
  src/tokens/config/fantom-tokens.config.ts
  src/tokens/config/polygon-tokens.config.ts
  src/tokens/interfaces/token-config.interface.ts
Labels: test
