Repository Badger-Finance/badger-api, pull requests merged in 2022-04, with the labels that each got.

#1113 fix: select appropriate harvest list
  src/vaults/__snapshots__/vaults.utils.spec.ts.snap
  src/vaults/vaults.utils.ts
Labels: bug

#1116 chore: add usdc-dei vault
  src/chains/config/fantom.config.ts
  src/config/tokens.config.ts
  src/indexers/vault-snapshots-indexer.spec.ts
  src/metrics/__snapshots__/metrics.utils.spec.ts.snap
  src/protocols/strategies/convex.strategy.ts
  src/tokens/config/fantom-tokens.config.ts
Labels: enhancement

#1114 test(badger-api): Add `gas.service.spec.ts`
  src/gas/gas.service.spec.ts
Labels: test

#1117 chore: add dei price
  src/config/tokens.config.ts
  src/tokens/config/fantom-tokens.config.ts
Labels: enhancement

#1111 release: curve crypto factory update + oxd ecosystem vaults
  src/chains/config/fantom.config.ts
  src/chains/config/xdai.config.ts
  src/config/rpc.config.ts
  src/config/tokens.config.ts
  src/gas/gas.service.spec.ts
  src/indexers/vault-snapshots-indexer.spec.ts
  src/protocols/strategies/convex.strategy.ts
  src/test/tests.utils.ts
  src/tokens/config/fantom-tokens.config.ts
  src/vaults/__snapshots__/vaults.utils.spec.ts.snap
  src/vaults/vaults.utils.ts
Labels: enhancement, on hold

#1118 chore: deprecate vaults
  src/chains/config/fantom.config.ts
Labels: enhancement

#1119 chore: update dei price addres
  src/config/tokens.config.ts
Labels: bug

#1122 release: bbtc apr + tests fix
  src/chains/config/fantom.config.ts
  src/config/tokens.config.ts
  src/indexers/vault-snapshots-indexer.spec.ts
  src/tokens/config/xdai-tokens.config.ts
  src/vaults/vaults.utils.ts
Labels: bug, enhancement

#1123 chore: release oxd vaults
  src/chains/config/fantom.config.ts
  src/metrics/__snapshots__/metrics.utils.spec.ts.snap
Labels: enhancement

#1125 release: oxd lp + oxsolid vault
  src/chains/config/fantom.config.ts
  src/metrics/__snapshots__/metrics.utils.spec.ts.snap
Labels: enhancement

#1128 chore: update api sdk version
  package.json
  src/chains/config/bsc.config.ts
  src/chains/config/eth.config.ts
  src/chains/config/fantom.config.ts
  src/vaults/__snapshots__/vaults.controller.spec.ts.snap
  src/vaults/vaults.service.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
  yarn.lock
Labels: enhancement

#1129 enhancement(vault): add bveoxd-lp apr logic
  src/protocols/strategies/oxdao.strategy.ts
Labels: enhancement

#1130 chore: deprecate uncared for vaults
  src/chains/config/eth.config.ts
  src/rewards/rewards.utils.ts
  src/vaults/__snapshots__/vaults.controller.spec.ts.snap
Labels: enhancement

#1132 fix: main staging merge
  seed/prices.json
  seed/vault-snapshots.json
  src/protocols/strategies/oxdao.strategy.ts
Labels: enhancement

#1133 fix: update source key overlap
  src/protocols/strategies/convex.strategy.ts
  src/protocols/strategies/oxdao.strategy.ts
  src/vaults/__snapshots__/vaults.utils.spec.ts.snap
  src/vaults/vaults.utils.ts
Labels: bug

#1134 fix: change accumulator params
  src/protocols/strategies/convex.strategy.ts
  src/protocols/strategies/oxdao.strategy.ts
Labels: bug

#1131 release: sdk update + deprecation
  package.json
  seed/prices.json
  seed/vault-snapshots.json
  src/chains/config/bsc.config.ts
  src/chains/config/eth.config.ts
  src/chains/config/fantom.config.ts
  src/protocols/strategies/convex.strategy.ts
  src/protocols/strategies/oxdao.strategy.ts
  src/rewards/rewards.utils.ts
  src/vaults/__snapshots__/vaults.controller.spec.ts.snap
  src/vaults/__snapshots__/vaults.utils.spec.ts.snap
  src/vaults/vaults.service.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
  yarn.lock
Labels: bug, enhancement

#1137 chore: cleanup unused abi
  src/abi/badger-tree.abi
  src/abi/controller.abi
  src/abi/cvx-booster.abi
  src/abi/cvx-chef.abi
  src/abi/cvx-locker.abi
  src/abi/cvx-rewards.abi
  src/abi/digg.abi
  src/abi/distributor.abi
  src/abi/erc20.abi
  src/abi/rewards-logger.abi
  src/abi/strategy.abi
  src/abi/sushi-chef.abi
  src/abi/sushi-mini-chef.abi
  src/abi/vault.abi
  src/contracts/BadgerTree.d.ts
  src/contracts/Controller.d.ts
  src/contracts/CurvePoolV2.d.ts
  src/contracts/CvxBooster.d.ts
  src/contracts/CvxChef.d.ts
  src/contracts/CvxLocker.d.ts
  src/contracts/CvxRewards.d.ts
  src/contracts/Digg.d.ts
  src/contracts/Distributor.d.ts
  src/contracts/Emp.d.ts
  src/contracts/Erc20.d.ts
  src/contracts/PancakeChef.d.ts
  src/contracts/RewardsLogger.d.ts
  src/contracts/Sett.d.ts
  src/contracts/Strategy.d.ts
  src/contracts/SushiChef.d.ts
  src/contracts/SushiMiniChef.d.ts
  src/contracts/Vault.d.ts
  src/contracts/commons.ts
  src/contracts/factories/BadgerTree__factory.ts
  src/contracts/factories/Controller__factory.ts
  src/contracts/factories/CurvePoolV2__factory.ts
  src/contracts/factories/CvxBooster__factory.ts
  src/contracts/factories/CvxChef__factory.ts
  src/contracts/factories/CvxLocker__factory.ts
  src/contracts/factories/CvxRewards__factory.ts
  src/contracts/factories/Digg__factory.ts
  src/contracts/factories/Distributor__factory.ts
  src/contracts/factories/Emp__factory.ts
  src/contracts/factories/Erc20__factory.ts
  src/contracts/factories/PancakeChef__factory.ts
  src/contracts/factories/RewardsLogger__factory.ts
  src/contracts/factories/Sett__factory.ts
  src/contracts/factories/Strategy__factory.ts
  src/contracts/factories/SushiChef__factory.ts
  src/contracts/factories/SushiMiniChef__factory.ts
  src/contracts/factories/Vault__factory.ts
  src/contracts/index.ts
  src/prices/custom/remdigg-price.ts
  src/protocols/strategies/convex.strategy.ts
  src/rewards/rewards.utils.ts
Labels: enhancement

#1139 chore: remove etherscan support
  src/common/request.ts
  src/etherscan/enums/etherscan-action.enum.ts
  src/etherscan/enums/etherscan-module.enum.ts
  src/etherscan/etherscan.utils.ts
  src/etherscan/interfaces/etherscan-block-response.interface.ts
  src/prices/prices.utils.spec.ts
  src/prices/prices.utils.ts
  src/protocols/strategies/convex.strategy.ts
Labels: enhancement

#1141 chore: deprecate stable coin vaults
  src/chains/config/eth.config.ts
  src/vaults/__snapshots__/vaults.controller.spec.ts.snap
Labels: enhancement

#1146 fix: setts controller param matching
  src/vaults/setts.controller.ts
Labels: bug

#1147 fix: setts controller param mismatch
  package.json
  src/vaults/setts.controller.ts
Labels: bug

#1150 fix: set floor gas price
  src/chains/config/chain.config.ts
  src/config/constants.ts
  src/protocols/strategies/sushiswap.strategy.ts
Labels: bug

#1151 release: arbitrum gas fix
  src/chains/config/chain.config.ts
  src/config/constants.ts
  src/protocols/strategies/sushiswap.strategy.ts
Labels: bug

#1157 chore: initial citadel treasury indexer
  serverless.yml
  src/aws/models/historic-treasury-summary-snapshot.model.ts
  src/aws/models/treasury-summary-snapshot.model.ts
  src/citadel/citadel-indexer.ts
  src/citadel/citadel.controller.ts
  src/citadel/citadel.service.ts
  src/citadel/config/citadel-treasury.config.ts
  src/citadel/interfaces/citadel-treasury-summary.interface.ts
  src/citadel/interfaces/index.ts
  src/config/constants.ts
  src/treasury/interfaces/cached-treasury-position.ts
  src/treasury/interfaces/treasury-summary.interface.ts
  src/treasury/interfaces/treasy-position.interface.ts
  src/treasury/treasury.utils.ts
Labels: enhancement

#1158 chore: add initial citadel treasury endpoint
  src/CitadelControllerRegistry.ts
  src/ControllerRegistry.ts
  src/Server.ts
  src/citadel/citadel-indexer.ts
  src/citadel/citadel.controller.ts
  src/citadel/citadel.service.ts
  src/citadel/interfaces/citadel-treasury-summary-model.interface.ts
  src/citadel/interfaces/citadel-treasury-summary.interface.ts
Labels: enhancement

#1159 fix: update job name
  serverless.yml
Labels: bug

#1160 chore: initial citadel tests
  package.json
  src/citadel/citadel.controller.spec.ts
  src/citadel/citadel.service.spec.ts
  src/rewards/__snapshots__/reward.controller.spec.ts.snap
  src/treasury/examples/treasury-summary.mock.ts
  yarn.lock
Labels: test

#1163 fix: update apy snapshotting task timeout
  serverless.yml
  src/rewards/rewards.utils.ts
Labels: bug

#1165 fix: update rewards sdk
  package.json
  src/rewards/__snapshots__/reward.controller.spec.ts.snap
  yarn.lock
Labels: bug

#1166 Release: sdk update + harvests optimization
  package.json
  src/rewards/__snapshots__/reward.controller.spec.ts.snap
  yarn.lock
Labels: bug, enhancement

#1161 chore: add arbitrary aws data table
  package.json
  serverless.yml
  src/aws/models/keyed-data-blob.model.ts
  src/aws/types/convertable-data-blob.ts
  src/aws/types/data-blob.ts
  src/citadel/citadel-indexer.ts
  src/citadel/citadel.controller.spec.ts
  src/citadel/citadel.controller.ts
  src/citadel/citadel.service.spec.ts
  src/citadel/citadel.service.ts
  src/citadel/citadel.utils.ts
  src/citadel/interfaces/citadel-data.interface.ts
  src/citadel/interfaces/citadel-treasury-summary-model.interface.ts
  src/citadel/interfaces/citadel-treasury-summary.interface.ts
  src/citadel/interfaces/index.ts
  src/config/constants.ts
  src/config/tokens.config.ts
  src/prices/__snapshots__/prices.controller.spec.ts.snap
  src/prices/__snapshots__/prices.service.spec.ts.snap
  src/protocols/strategies/convex.strategy.ts
  src/tokens/config/eth-tokens.config.ts
  src/treasury/treasury.utils.ts
  yarn.lock
Labels: enhancement

#1168 chore: create keyed precomputed chart data
  seed/prices.json
  serverless.yml
  src/aws/models/chart-data-blob.model.ts
  src/aws/models/historic-treasury-summary-snapshot.model.ts
  src/charts/charts.utils.ts
  src/charts/enums/chart-timeframe.enum.ts
  src/citadel/citadel-indexer.ts
  src/citadel/citadel.controller.ts
  src/config/constants.ts
  src/treasury/treasury-indexer.ts
  src/treasury/treasury.service.ts
  src/treasury/treasury.utils.ts
Labels: enhancement

#1171 chore: update citadel service test snapshots
  package.json
  src/citadel/citadel.controller.spec.ts
  src/citadel/citadel.service.spec.ts
  src/treasury/treasury-indexer.ts
  yarn.lock
Labels: bug

#1172 chore: support ust
  src/config/tokens.config.ts
  src/prices/__snapshots__/prices.controller.spec.ts.snap
  src/prices/__snapshots__/prices.service.spec.ts.snap
  src/tokens/config/eth-tokens.config.ts
Labels: enhancement

#1173 chore: update sdk + update citadel response
  package.json
  src/citadel/__snapshots__/citadel.controller.spec.ts.snap
  src/citadel/citadel.controller.spec.ts
  src/citadel/citadel.service.ts
  src/citadel/interfaces/citadel-reward-event-model.interface.ts
  src/citadel/interfaces/citadel-treasury-summary-model.interface.ts
  src/citadel/mocks/citadel-reward-events.mock.ts
  yarn.lock
Labels: enhancement

#1170 release: initial citadel charts + user rewards
  package.json
  seed/prices.json
  serverless.yml
  src/aws/models/chart-data-blob.model.ts
  src/aws/models/historic-treasury-summary-snapshot.model.ts
  src/aws/models/keyed-data-blob.model.ts
  src/aws/types/convertable-data-blob.ts
  src/aws/types/data-blob.ts
  src/charts/charts.utils.ts
  src/charts/enums/chart-timeframe.enum.ts
  src/citadel/__snapshots__/citadel.controller.spec.ts.snap
  src/citadel/citadel-indexer.ts
  src/citadel/citadel.controller.spec.ts
  src/citadel/citadel.controller.ts
  src/citadel/citadel.service.spec.ts
  src/citadel/citadel.service.ts
  src/citadel/citadel.utils.ts
  src/citadel/interfaces/citadel-data.interface.ts
  src/citadel/interfaces/citadel-reward-event-model.interface.ts
  src/citadel/interfaces/citadel-reward-event.interface.ts
  src/citadel/interfaces/citadel-treasury-summary-model.interface.ts
  src/citadel/interfaces/citadel-treasury-summary.interface.ts
  src/citadel/interfaces/index.ts
  src/citadel/mocks/citadel-reward-events.mock.ts
  src/config/constants.ts
  src/config/tokens.config.ts
  src/prices/__snapshots__/prices.controller.spec.ts.snap
  src/prices/__snapshots__/prices.service.spec.ts.snap
  src/protocols/strategies/convex.strategy.ts
  src/tokens/config/eth-tokens.config.ts
  src/treasury/treasury-indexer.ts
  src/treasury/treasury.service.ts
  src/treasury/treasury.utils.ts
  yarn.lock
Labels: on hold

#1174 chore: remove binance from account indexing
  src/indexers/accounts-indexer.ts
Labels: enhancement
