Repository Badger-Finance/badger-api, pull requests merged in 2022-11, with the labels that each got.

#1586 fix: properly scale user balance
  src/accounts/accounts.utils.ts
  src/tokens/tokens.utils.spec.ts
  src/tokens/tokens.utils.ts
Labels: bug

#1587 fix: user balance update
  src/accounts/accounts.utils.ts
  src/tokens/tokens.utils.spec.ts
  src/tokens/tokens.utils.ts
Labels: bug

#1588 chore: update logging + cache
  src/Server.ts
Labels: bug

#1590 test: resolve test timeout
  src/indexers/__snapshots__/indexer.utils.spec.ts.snap
  src/indexers/indexer.utils.spec.ts
  src/test/constants.ts
Labels: test

#1591 Draft: feat: governance proposals init plus indexer
  package.json
  serverless.yml
  src/aws/models/governance-proposals-child.interface.ts
  src/aws/models/governance-proposals-disputes.interface.ts
  src/aws/models/governance-proposals-statuses.interface.ts
  src/aws/models/governance-proposals.model.ts
  src/config/constants.ts
  src/controllers.ts
  src/errors/enums/error.codes.enum.ts
  src/errors/internal/ddb.error.ts
  src/errors/internal/internal.error.ts
  src/errors/validation/out.of.range.error.ts
  src/governance/governance.constants.ts
  src/governance/governance.controller.ts
  src/governance/governance.service.ts
  src/governance/governance.utils.ts
  src/governance/interfaces/governance.proposals.list.ts
  src/governance/responses/proposal.list.response.ts
  src/governance/responses/proposal.response.ts
  src/indexers/governance-proposals-indexer.ts
  yarn.lock
Labels: enhancement

#1593 chore: hide governance in production
  src/errors/allocation/not.found.error.ts
  src/errors/enums/error.codes.enum.ts
  src/governance/governance.controller.ts
Labels: enhancement
