Repository Badger-Finance/badger-api, pull requests merged in 2022-03, with the labels that each got.

#937 chore: add vault derivate apy
  src/charts/charts.service.spec.ts
  src/protocols/protocols.utils.ts
  src/test/tests.utils.ts
  src/vaults/__snapshots__/vaults.utils.spec.ts.snap
  src/vaults/vaults.controller.spec.ts
  src/vaults/vaults.service.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
Labels: enhancement

#938 chore: add helper definitions
  package.json
  src/chains/config/fantom.config.ts
  src/config/tokens.config.ts
  yarn.lock
Labels: enhancement

#939 chore: add fantom helper vault prices
  src/tokens/config/fantom-tokens.config.ts
Labels: enhancement

#940 fix: change apr power operator from xor
  src/indexers/apy-snapshots-indexer.spec.ts
  src/indexers/apy-snapshots-indexer.ts
  src/rewards/rewards.utils.ts
  src/vaults/__snapshots__/vaults.utils.spec.ts.snap
  src/vaults/vaults.utils.ts
Labels: bug

#941 chore: update test path for old source deletion
  src/indexers/apy-snapshots-indexer.spec.ts
  src/test/tests.utils.ts
Labels: enhancement

#942 chore: handle no expected file
  src/rewards/rewards.utils.ts
Labels: bug

#944 chore: add solidsex price
  src/config/tokens.config.ts
  src/tokens/config/fantom-tokens.config.ts
  yarn.lock
Labels: enhancement

#943 fix: update derivative apr calculations
  package.json
  src/chains/config/chain.config.ts
  src/indexers/apy-snapshots-indexer.ts
  src/protocols/common/swap.utils.ts
  src/protocols/strategies/mstable.strategy.ts
  src/rewards/enums/source-type.enum.ts
  src/rewards/rewards.utils.ts
  src/vaults/__snapshots__/vaults.utils.spec.ts.snap
  src/vaults/vaults.service.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
  yarn.lock
Labels: bug

#945 chore: update price seeding + error messaging
  seed/prices.json
  seed/scripts/update-prices.ts
  src/indexers/token-balances-indexer.ts
  src/indexers/vault-snapshots-indexer.ts
Labels: enhancement, on hold

#947 chore: update lp vault apr calculation
  src/protocols/strategies/convex.strategy.ts
  src/rewards/rewards.utils.ts
  src/test/tests.utils.ts
  src/vaults/vaults.utils.ts
Labels: enhancement

#948 chore: export apy performance metrics
  package.json
  src/vaults/__snapshots__/vaults.controller.spec.ts.snap
  src/vaults/interfaces/vault-model.interface.ts
  src/vaults/vaults.service.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
  yarn.lock
Labels: enhancement

#949 chore: deprecate mstable vaults
  src/chains/config/eth.config.ts
  src/vaults/__snapshots__/vaults.controller.spec.ts.snap
Labels: enhancement

#950 chore: add weve vault definitions
  src/chains/config/fantom.config.ts
  src/config/tokens.config.ts
  src/tokens/config/fantom-tokens.config.ts
Labels: enhancement

#951 chore: divide apr prior to use
  src/vaults/__snapshots__/vaults.utils.spec.ts.snap
  src/vaults/vaults.utils.ts
Labels: bug

#953 fix: update division + parents on derivative apr calculations
  src/vaults/__snapshots__/vaults.utils.spec.ts.snap
  src/vaults/vaults.utils.ts
Labels: bug

#955 chore: add oxd vault
  src/chains/config/fantom.config.ts
  src/config/tokens.config.ts
  src/tokens/config/fantom-tokens.config.ts
Labels: enhancement

#954 chore: add weighted estimates
  src/indexers/indexer.utils.ts
  src/vaults/__snapshots__/vaults.utils.spec.ts.snap
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
Labels: enhancement

#956 release: apy estimation update
  .github/ISSUE_TEMPLATE/feature_request.md
  package.json
  seed/prices.json
  seed/scripts/update-prices.ts
  serverless.yml
  src/ControllerRegistry.ts
  src/chains/config/chain.config.ts
  src/chains/config/eth.config.ts
  src/chains/config/fantom.config.ts
  src/chains/strategies/base.strategy.ts
  src/charts/charts.service.spec.ts
  src/config/constants.ts
  src/config/tokens.config.ts
  src/health/apis-health.service.ts
  src/health/contracts-health.service.ts
  src/health/health.config.ts
  src/health/health.controller.ts
  src/health/health.interface.ts
  src/health/health.service.spec.ts
  src/health/health.types.ts
  src/health/health.utils.ts
  src/health/providers-health.service.ts
  src/health/subgraphs-health.service.ts
  src/indexers/apy-snapshots-indexer.spec.ts
  src/indexers/apy-snapshots-indexer.ts
  src/indexers/indexer.utils.ts
  src/indexers/price-indexer.ts
  src/indexers/token-balances-indexer.ts
  src/indexers/vault-snapshots-indexer.spec.ts
  src/indexers/vault-snapshots-indexer.ts
  src/prices/__snapshots__/prices.controller.spec.ts.snap
  src/prices/__snapshots__/prices.service.spec.ts.snap
  src/prices/enums/pricing-type.enum.ts
  src/proofs/proofs.service.spec.ts
  src/proofs/proofs.service.ts
  src/protocols/common/swap.utils.ts
  src/protocols/protocols.utils.ts
  src/protocols/strategies/convex.strategy.ts
  src/protocols/strategies/mstable.strategy.ts
  src/protocols/strategies/swapr.strategy.ts
  src/rewards/enums/source-type.enum.ts
  src/rewards/rewards.utils.ts
  src/test/tests.utils.ts
  src/tokens/__snapshots__/tokens.controller.spec.ts.snap
  src/tokens/config/eth-tokens.config.ts
  src/tokens/config/fantom-tokens.config.ts
  src/tokens/tokens.utils.ts
  src/vaults/__snapshots__/vaults.controller.spec.ts.snap
  src/vaults/__snapshots__/vaults.service.spec.ts.snap
  src/vaults/__snapshots__/vaults.utils.spec.ts.snap
  src/vaults/interfaces/vault-model.interface.ts
  src/vaults/vaults.controller.spec.ts
  src/vaults/vaults.service.spec.ts
  src/vaults/vaults.service.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
  yarn.lock
Labels: enhancement

#959 chore: update renbtc vault
  src/chains/config/fantom.config.ts
  src/config/tokens.config.ts
Labels: enhancement

#960 chore: add high apy vaults
  src/chains/config/fantom.config.ts
  src/config/tokens.config.ts
  src/tokens/config/fantom-tokens.config.ts
Labels: enhancement

#961 fix: add b to token asset
  src/tokens/config/fantom-tokens.config.ts
  src/vaults/__snapshots__/vaults.utils.spec.ts.snap
  src/vaults/vaults.utils.ts
Labels: bug

#962 fix: enforce period max
  src/vaults/vaults.utils.ts
Labels: enhancement

#963 chore: update derivative apy maths
  src/vaults/__snapshots__/vaults.utils.spec.ts.snap
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
Labels: enhancement

#965 chore: maximize window
  src/vaults/__snapshots__/vaults.utils.spec.ts.snap
  src/vaults/vaults.utils.ts
Labels: enhancement

#966 chore: bump vault stage
  src/chains/config/fantom.config.ts
  src/metrics/__snapshots__/metrics.utils.spec.ts.snap
Labels: enhancement

#970 chore: add geist definitions
  src/chains/config/fantom.config.ts
  src/config/tokens.config.ts
  src/contracts/CurvePoolOld.d.ts
  src/contracts/CurvePoolPolygon.d.ts
  src/contracts/factories/CurvePoolOld__factory.ts
  src/contracts/factories/CurvePoolPolygon__factory.ts
  src/protocols/strategies/convex.strategy.ts
  src/tokens/config/fantom-tokens.config.ts
  src/vaults/__snapshots__/vaults.utils.spec.ts.snap
  src/vaults/vaults.utils.ts
Labels: enhancement, on hold

#969 release: fantom vault launch
  src/chains/config/fantom.config.ts
  src/config/tokens.config.ts
  src/contracts/CurvePoolOld.d.ts
  src/contracts/CurvePoolPolygon.d.ts
  src/contracts/factories/CurvePoolOld__factory.ts
  src/contracts/factories/CurvePoolPolygon__factory.ts
  src/metrics/__snapshots__/metrics.utils.spec.ts.snap
  src/protocols/strategies/convex.strategy.ts
  src/tokens/config/fantom-tokens.config.ts
  src/vaults/__snapshots__/vaults.utils.spec.ts.snap
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
Labels: enhancement, on hold

#972 chore: add dca vault flag
  src/chains/config/fantom.config.ts
  src/tokens/config/fantom-tokens.config.ts
  src/vaults/__snapshots__/vaults.controller.spec.ts.snap
  src/vaults/interfaces/vault-definition.interface.ts
  src/vaults/interfaces/vault-model.interface.ts
  src/vaults/vaults.service.ts
Labels: enhancement

#973 chore: update sdk integration
  package.json
  src/vaults/interfaces/vault-model.interface.ts
  src/vaults/vaults.service.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
  yarn.lock
Labels: enhancement

#975 release: dca boolean indicator
  package.json
  src/chains/config/fantom.config.ts
  src/tokens/config/fantom-tokens.config.ts
  src/vaults/__snapshots__/vaults.controller.spec.ts.snap
  src/vaults/interfaces/vault-definition.interface.ts
  src/vaults/interfaces/vault-model.interface.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
  yarn.lock
Labels: enhancement

#976 chore: add initial ecosystem vaults
  src/accounts/accounts.utils.spec.ts
  src/chains/config/fantom.config.ts
  src/config/tokens.config.ts
  src/tokens/config/fantom-tokens.config.ts
Labels: enhancement

#980 chore: update vaults snapshots indexer + entity storrage
  seed/prices.json
  src/config/constants.ts
  src/indexers/indexer.utils.ts
  src/indexers/vault-snapshots-indexer.spec.ts
  src/indexers/vault-snapshots-indexer.ts
  src/test/tests.utils.ts
  src/vaults/interfaces/cached-vault-snapshot.interface.ts
  src/vaults/interfaces/vault-snapshot.interface.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
Labels: enhancement

#983 fix: backport vaul snapshots + update geist ecosystem designation
  src/chains/config/fantom.config.ts
  src/config/tokens.config.ts
  src/tokens/config/fantom-tokens.config.ts
  src/vaults/interfaces/vault-snapshot.interface.ts
  src/vaults/vaults.utils.ts
Labels: bug

#984 chore: add gas spread
  src/chains/config/chain.config.ts
Labels: bug

#988 chore: release ecosystem vaults
  src/chains/config/fantom.config.ts
  src/metrics/__snapshots__/metrics.utils.spec.ts.snap
Labels: enhancement

#989 fix: do not overwrite existing ppfs
  src/chains/config/fantom.config.ts
  src/metrics/__snapshots__/metrics.utils.spec.ts.snap
  src/vaults/vaults.utils.ts
Labels: bug

#991 chore: reactor 1 to 1 mapping for cached vault tokens balances
  serverless.yml
  src/config/constants.ts
  src/indexers/indexer.utils.ts
  src/indexers/vault-balances-indexer.spec.ts
  src/indexers/vault-balances-indexer.ts
  src/protocols/strategies/convex.strategy.ts
  src/tokens/interfaces/cached-liquidity-pool-token-balance.interface.ts
  src/tokens/interfaces/cached-vault-token-balance.interface.ts
  src/tokens/tokens.utils.spec.ts
  src/tokens/tokens.utils.ts
  src/vaults/interfaces/vault-definition.interface.ts
Labels: bug

#992 release: token balances updates
  serverless.yml
  src/chains/config/fantom.config.ts
  src/config/constants.ts
  src/indexers/indexer.utils.ts
  src/indexers/vault-balances-indexer.spec.ts
  src/indexers/vault-balances-indexer.ts
  src/metrics/__snapshots__/metrics.utils.spec.ts.snap
  src/protocols/strategies/convex.strategy.ts
  src/tokens/interfaces/cached-liquidity-pool-token-balance.interface.ts
  src/tokens/interfaces/cached-vault-token-balance.interface.ts
  src/tokens/tokens.utils.spec.ts
  src/tokens/tokens.utils.ts
  src/vaults/interfaces/vault-definition.interface.ts
  src/vaults/vaults.utils.ts
Labels: enhancement

#999 chore: deprecate vaults
  src/chains/config/eth.config.ts
  src/vaults/__snapshots__/vaults.controller.spec.ts.snap
  src/vaults/interfaces/vault-definition.interface.ts
  src/vaults/vaults.service.ts
Labels: enhancement

#1001 chore: remove mstable custom code
  src/protocols/strategies/mstable.strategy.ts
  src/rewards/rewards.utils.ts
Labels: enhancement

#1003 feat: complete dynamic vault apr migration
  package.json
  seed/prices.json
  src/abi/emp.abi
  src/abi/pancake-chef.abi
  src/abi/sett.abi
  src/accounts/accounts.utils.ts
  src/chains/config/arbitrum.config.ts
  src/chains/config/avax.config.ts
  src/chains/config/bsc.config.ts
  src/chains/config/chain.config.ts
  src/chains/config/eth.config.ts
  src/chains/config/fantom.config.ts
  src/chains/config/polygon.config.ts
  src/chains/config/xdai.config.ts
  src/contracts/index.ts
  src/indexers/apy-snapshots-indexer.ts
  src/indexers/vaults-indexer.spec.ts
  src/protocols/interfaces/cached-value-source.interface.ts
  src/protocols/interfaces/performance.interface.ts
  src/protocols/interfaces/value-source.interface.ts
  src/protocols/strategies/convex.strategy.ts
  src/protocols/strategies/mstable.strategy.ts
  src/protocols/strategies/strategy.utils.ts
  src/protocols/strategies/sushiswap.strategy.ts
  src/protocols/strategies/swapr.strategy.ts
  src/rewards/enums/source-timeframe.enum.ts
  src/rewards/rewards.utils.spec.ts
  src/rewards/rewards.utils.ts
  src/test/tests.utils.ts
  src/vaults/__snapshots__/vaults.controller.spec.ts.snap
  src/vaults/__snapshots__/vaults.utils.spec.ts.snap
  src/vaults/interfaces/vault-harvest-data.interface.ts
  src/vaults/interfaces/vault-model.interface.ts
  src/vaults/vaults.controller.spec.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
  yarn.lock
Labels: enhancement

#1008 chore: update sdk + use strategy balance for apr
  package.json
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
  yarn.lock
Labels: enhancement

#1010 chore: add vault fallbacks
  src/accounts/accounts.utils.ts
  src/rewards/rewards.utils.ts
  src/vaults/vaults.utils.ts
Labels: bug

#1011 release: dyanmic vault apr upgrade
  package.json
  seed/prices.json
  src/abi/emp.abi
  src/abi/pancake-chef.abi
  src/abi/sett.abi
  src/accounts/accounts.utils.ts
  src/chains/config/arbitrum.config.ts
  src/chains/config/avax.config.ts
  src/chains/config/bsc.config.ts
  src/chains/config/chain.config.ts
  src/chains/config/eth.config.ts
  src/chains/config/fantom.config.ts
  src/chains/config/polygon.config.ts
  src/chains/config/xdai.config.ts
  src/contracts/index.ts
  src/indexers/apy-snapshots-indexer.ts
  src/indexers/vaults-indexer.spec.ts
  src/protocols/interfaces/cached-value-source.interface.ts
  src/protocols/interfaces/performance.interface.ts
  src/protocols/interfaces/value-source.interface.ts
  src/protocols/strategies/convex.strategy.ts
  src/protocols/strategies/mstable.strategy.ts
  src/protocols/strategies/strategy.utils.ts
  src/protocols/strategies/sushiswap.strategy.ts
  src/protocols/strategies/swapr.strategy.ts
  src/rewards/enums/source-timeframe.enum.ts
  src/rewards/examples/reward-schedules-vaults.mock.ts
  src/rewards/interfaces/reward-schedules-vault-model.interface.ts
  src/rewards/interfaces/reward-schedules-vault.interface.ts
  src/rewards/interfaces/reward-schedules-vaults-model.interface.ts
  src/rewards/rewards.controller.ts
  src/rewards/rewards.service.ts
  src/rewards/rewards.utils.spec.ts
  src/rewards/rewards.utils.ts
  src/test/tests.utils.ts
  src/vaults/__snapshots__/vaults.controller.spec.ts.snap
  src/vaults/__snapshots__/vaults.utils.spec.ts.snap
  src/vaults/interfaces/vault-harvest-data.interface.ts
  src/vaults/interfaces/vault-model.interface.ts
  src/vaults/vaults.controller.spec.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
  yarn.lock
Labels: enhancement

#1014 chore: save historic apr
  src/indexers/vaults-indexer.spec.ts
  src/indexers/vaults-indexer.ts
  src/rewards/rewards.controller.ts
  src/vaults/setts.controller.ts
  src/vaults/types/historic-vault-snapshot.ts
  src/vaults/vaults.controller.ts
  src/vaults/vaults.service.ts
Labels: enhancement

#1020 fix: use larger number as upper bound
  src/vaults/vaults.utils.ts
Labels: bug

#1021 fix: use ratio fallback
  src/vaults/vaults.utils.ts
Labels: bug

#1022 fix: correct ppfs test maths
  package.json
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
  yarn.lock
Labels: bug

#1023 release: sdk bug fixes update + fallback ppfs apr estimation
  package.json
  src/charts/charts.controller.ts
  src/charts/charts.service.ts
  src/config/constants.ts
  src/indexers/indexer.utils.ts
  src/indexers/vault-snapshots-indexer.spec.ts
  src/indexers/vault-snapshots-indexer.ts
  src/indexers/vaults-indexer.spec.ts
  src/indexers/vaults-indexer.ts
  src/test/tests.utils.ts
  src/vaults/interfaces/vault-snapshot.interface.ts
  src/vaults/types/current-vault-snapshot.ts
  src/vaults/types/historic-vault-snapshot.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
  yarn.lock
Labels: bug, enhancement

#1026 chore: add assume role request
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/deploy.yml
Labels: enhancement

#1027 release: oidc based deployment pipeline
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/deploy.yml
Labels: enhancement

#1028 fix: remove test code linkage
  src/tokens/mocks/full-token.mock.ts
Labels: bug

#1025 chore: fix packages version
  .github/workflows/coverage.yml
  package.json
  yarn.lock
Labels: enhancement

#1033 chore: add vault 1.5 yield projection
  package.json
  src/accounts/accounts.utils.spec.ts
  src/chains/strategies/test.strategy.ts
  src/indexers/indexer.utils.ts
  src/metrics/metrics.utils.spec.ts
  src/protocols/common/swap.utils.ts
  src/protocols/strategies/convex.strategy.ts
  src/protocols/strategies/mstable.strategy.ts
  src/test/tests.utils.ts
  src/tokens/interfaces/cached-token-balance.interface.ts
  src/tokens/tokens.utils.spec.ts
  src/tokens/tokens.utils.ts
  src/vaults/__snapshots__/vaults.controller.spec.ts.snap
  src/vaults/interfaces/vault-harvest-data.interface.ts
  src/vaults/interfaces/vault-model.interface.ts
  src/vaults/types/current-vault-snapshot.ts
  src/vaults/types/historic-vault-snapshot.ts
  src/vaults/vaults.controller.spec.ts
  src/vaults/vaults.service.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
  yarn.lock
Labels: enhancement

#1034 chore: add harvest data infrastructure
  serverless.yml
  src/config/constants.ts
  src/indexers/indexer.utils.ts
  src/indexers/vault-balances-indexer.spec.ts
  src/indexers/vault-balances-indexer.ts
  src/protocols/strategies/convex.strategy.ts
  src/tokens/tokens.utils.ts
  src/vaults/interfaces/vault-definition.interface.ts
  src/vaults/types/vault-harvest-data.ts
  src/vaults/types/vault-token-balance.interface.ts
Labels: enhancement

#1036 chore: add harvest data addition
  package.json
  src/indexers/apy-snapshots-indexer.ts
  src/indexers/indexer.utils.ts
  src/indexers/vault-balances-indexer.spec.ts
  src/indexers/vault-harvest-indexer.ts
  src/indexers/vault-snapshots-indexer.spec.ts
  src/protocols/protocols.utils.ts
  src/protocols/strategies/convex.strategy.ts
  src/rewards/rewards.utils.ts
  src/test/tests.utils.ts
  src/tokens/tokens.utils.ts
  src/vaults/__snapshots__/vaults.controller.spec.ts.snap
  src/vaults/interfaces/vault-model.interface.ts
  src/vaults/types/current-vault-snapshot.ts
  src/vaults/types/historic-vault-snapshot.ts
  src/vaults/types/vault-pending-harvest-data.ts
  src/vaults/vaults.controller.spec.ts
  src/vaults/vaults.service.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
  yarn.lock
Labels: enhancement

#1040 Fix.deploy.pck
  .github/workflows/deploy.yml
  package.json
  src/charts/charts.service.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
  yarn.lock
Labels: enhancement

#1041 chore: add harvest cron
  serverless.yml
  src/indexers/vault-harvests-indexer.ts
  yarn.lock
Labels: enhancement

#1042 chore: add badger-wbtc vault
  src/chains/config/eth.config.ts
  src/config/tokens.config.ts
  src/prices/__snapshots__/prices.controller.spec.ts.snap
  src/prices/__snapshots__/prices.service.spec.ts.snap
  src/tokens/config/eth-tokens.config.ts
Labels: enhancement

#1044 fix: clean node modules on deploy
  .github/workflows/deploy.yml
  package.json
  serverless.yml
  src/etherscan/etherscan.utils.ts
  tsconfig.build.json
  yarn.lock
Labels: bug

#1045 chore: rename indexing event
  serverless.yml
Labels: bug

#1047 chore: add univ2 clause
  src/indexers/vault-balances-indexer.ts
  src/vaults/vaults.utils.ts
Labels: bug

#1048 chore: rename harvest event
  serverless.yml
Labels: bug

#1054 fix: yield projection implementation issues
  serverless.yml
  src/aws/s3.utils.ts
  src/indexers/indexer.utils.ts
  src/indexers/vault-snapshots-indexer.ts
  src/vaults/vaults.service.ts
  src/vaults/vaults.utils.ts
Labels: enhancement

#1055 fix: remapping issues
  seed/prices.json
  src/indexers/price-indexer.ts
  src/prices/__snapshots__/prices.utils.spec.ts.snap
  src/prices/prices.utils.spec.ts
  src/prices/prices.utils.ts
  src/tokens/tokens.utils.ts
  src/vaults/vaults.utils.ts
Labels: bug

#1056 chore: remove logging, update entity schema
  package.json
  src/aws/s3.utils.ts
  src/indexers/apy-snapshots-indexer.ts
  src/indexers/price-indexer.ts
  src/indexers/vault-snapshots-indexer.ts
  src/rewards/rewards.utils.ts
  src/tokens/tokens.utils.ts
  src/vaults/vaults.utils.ts
  yarn.lock
Labels: enhancement

#1058 chore: add back table
  serverless.yml
Labels: enhancement

#1059 chore: update token balance mocking
  src/accounts/interfaces/sett-balance.interface.ts
  src/indexers/indexer.utils.ts
  src/indexers/vault-snapshots-indexer.spec.ts
  src/prices/__snapshots__/prices.service.spec.ts.snap
  src/prices/prices.service.spec.ts
  src/test/tests.utils.ts
  src/tokens/__snapshots__/tokens.utils.spec.ts.snap
  src/tokens/interfaces/token-balance.interface.ts
  src/tokens/tokens.utils.spec.ts
  src/tokens/tokens.utils.ts
  src/vaults/__snapshots__/vaults.controller.spec.ts.snap
  src/vaults/vaults.controller.spec.ts
  src/vaults/vaults.service.ts
Labels: bug

#1060 chore: resolve single token balances
  src/accounts/accounts.utils.spec.ts
  src/accounts/accounts.utils.ts
  src/indexers/vault-snapshots-indexer.spec.ts
  src/protocols/strategies/convex.strategy.ts
  src/test/tests.utils.ts
  src/tokens/__snapshots__/tokens.utils.spec.ts.snap
  src/tokens/tokens.utils.spec.ts
  src/tokens/tokens.utils.ts
  src/vaults/vaults.controller.spec.ts
  src/vaults/vaults.service.ts
Labels: bug

#1062 fix: upgrade sdk version
  package.json
  seed/prices.json
  seed/scripts/update-tokens.ts
  seed/token-info.json
  src/indexers/vault-harvests-indexer.ts
  yarn.lock
Labels: bug

#1063 chore: add fantom vaults + add vault projection apy
  package.json
  src/chains/config/fantom.config.ts
  src/config/tokens.config.ts
  src/tokens/config/fantom-tokens.config.ts
  src/vaults/vaults.service.ts
  yarn.lock
Labels: enhancement

#1066 chore: remove bcvx compounding
  src/rewards/rewards.utils.ts
Labels: bug

#1072 chore: fix badger lookup name, add vaults version defs, add deus price
  package.json
  seed/prices.json
  seed/scripts/update-snapshots.ts
  seed/vault-snapshots.json
  src/chains/config/avax.config.ts
  src/chains/config/fantom.config.ts
  src/config/tokens.config.ts
  src/indexers/indexer.utils.ts
  src/indexers/price-indexer.ts
  src/tokens/config/eth-tokens.config.ts
  src/tokens/config/fantom-tokens.config.ts
  src/tokens/mocks/full-token.mock.ts
  src/vaults/__snapshots__/vaults.controller.spec.ts.snap
  src/vaults/interfaces/vault-definition.interface.ts
  src/vaults/vaults.controller.spec.ts
  src/vaults/vaults.service.ts
  src/vaults/vaults.utils.ts
  yarn.lock
Labels: bug, enhancement

#1073 chore: update oxd locker
  src/chains/config/fantom.config.ts
  src/config/tokens.config.ts
  src/tokens/config/fantom-tokens.config.ts
Labels: bug

#1074 chore: add distrubtion tracking
  src/vaults/vaults.utils.ts
Labels: bug

#1075 relase: bvecvx apr fix + bveoxd address update
  package.json
  seed/prices.json
  seed/scripts/update-snapshots.ts
  seed/vault-snapshots.json
  src/chains/config/avax.config.ts
  src/chains/config/fantom.config.ts
  src/config/tokens.config.ts
  src/indexers/indexer.utils.ts
  src/indexers/price-indexer.ts
  src/rewards/rewards.utils.ts
  src/tokens/config/eth-tokens.config.ts
  src/tokens/config/fantom-tokens.config.ts
  src/tokens/mocks/full-token.mock.ts
  src/vaults/__snapshots__/vaults.controller.spec.ts.snap
  src/vaults/interfaces/vault-definition.interface.ts
  src/vaults/vaults.controller.spec.ts
  src/vaults/vaults.service.ts
  src/vaults/vaults.utils.ts
  yarn.lock
Labels: bug

#1076 fix: require checksum addresses for tokens queries
  src/indexers/indexer.utils.ts
  src/prices/prices.utils.ts
  src/tokens/tokens.utils.ts
  src/vaults/vaults.service.ts
  src/vaults/vaults.utils.ts
Labels: bug

#1077 release: bvecvx apr fix + vault version fix
  src/indexers/indexer.utils.ts
  src/prices/prices.utils.ts
  src/tokens/tokens.utils.ts
  src/vaults/vaults.service.ts
  src/vaults/vaults.utils.ts
Labels: enhancement

#1078 fix: resolve bad if statement guard
  seed/cached-vault-snapshots.json
  seed/prices.json
  seed/scripts/update-snapshots.ts
  seed/vault-snapshots.json
  src/vaults/__snapshots__/vaults.controller.spec.ts.snap
  src/vaults/vaults.controller.spec.ts
  src/vaults/vaults.service.ts
Labels: bug

#1080 release: resolve yield projection null estimates
  seed/cached-vault-snapshots.json
  seed/prices.json
  seed/scripts/update-snapshots.ts
  seed/vault-snapshots.json
  src/vaults/__snapshots__/vaults.controller.spec.ts.snap
  src/vaults/vaults.controller.spec.ts
  src/vaults/vaults.service.ts
Labels: bug

#1081 chore: promote oxd
  src/chains/config/fantom.config.ts
  src/metrics/__snapshots__/metrics.utils.spec.ts.snap
Labels: enhancement

#1082 release: bveOXD vault
  src/chains/config/fantom.config.ts
  src/metrics/__snapshots__/metrics.utils.spec.ts.snap
Labels: documentation

#1083 chore: resolve div by 0 condition
  src/vaults/vaults.service.ts
Labels: bug

#1084 release: fix div by zero condition
  src/vaults/vaults.service.ts
Labels: bug

#1089 fix: persist token using checksum addr
  serverless.yml
  src/indexers/price-indexer.ts
  src/prices/prices.utils.ts
Labels: bug

#1090 bug fix: price update checksum addr
  serverless.yml
  src/chains/config/chain.config.ts
  src/indexers/price-indexer.ts
  src/prices/prices.utils.ts
  src/rewards/rewards.controller.ts
  src/tokens/mocks/full-token.mock.ts
  src/vaults/__snapshots__/vaults.controller.spec.ts.snap
  src/vaults/enums/harvest.enum.ts
  src/vaults/interfaces/vault-harvest-extended.ts
  src/vaults/interfaces/vault-harvest-map.ts
  src/vaults/interfaces/vault-harvests-list-model.interface.ts
  src/vaults/interfaces/vault-harvests-model.interface.ts
  src/vaults/mocks/vaults-graph-sdk-map.mock.ts
  src/vaults/mocks/vaults-harvests-map.mock.ts
  src/vaults/mocks/vaults-harvests-sdk.mock.ts
  src/vaults/vaults.controller.spec.ts
  src/vaults/vaults.controller.ts
  src/vaults/vaults.service.ts
  src/vaults/vaults.utils.ts
Labels: bug

#1092 chore: add vaults v1.5 fee support
  package.json
  src/chains/config/chain.config.ts
  src/indexers/vault-snapshots-indexer.spec.ts
  src/rewards/rewards.controller.ts
  src/test/tests.utils.ts
  src/vaults/__snapshots__/vaults.controller.spec.ts.snap
  src/vaults/interfaces/vault-strategy.interface.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
  yarn.lock
Labels: enhancement

#1093 release: vaults v1.5 fees
  package.json
  src/chains/config/chain.config.ts
  src/indexers/vault-snapshots-indexer.spec.ts
  src/rewards/rewards.controller.ts
  src/test/tests.utils.ts
  src/vaults/__snapshots__/vaults.controller.spec.ts.snap
  src/vaults/interfaces/vault-strategy.interface.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
  yarn.lock
Labels: enhancement

#1095 feat: add vault v1 harvests
  src/indexers/vault-harvests-indexer.ts
Labels: enhancement

#1096 release: debank api fix + v1 last harvest support
  src/chains/config/chain.config.ts
  src/indexers/vault-harvests-indexer.ts
  src/rewards/rewards.controller.ts
Labels: enhancement

#1099 release: include tree distributions
  src/indexers/vault-harvests-indexer.ts
Labels: enhancement

#1102 chore: mark wbtc-badger as new
  src/chains/config/eth.config.ts
  src/vaults/__snapshots__/vaults.controller.spec.ts.snap
Labels: enhancement

#1103 release: wbtc-badger promotion + distribution harvest fix
  README.md
  src/chains/config/eth.config.ts
  src/indexers/vault-harvests-indexer.ts
  src/vaults/__snapshots__/vaults.controller.spec.ts.snap
Labels: bug, enhancement

#1104 chore: force vault update
  src/indexers/indexer.utils.ts
Labels: bug

#1105 fix: force update vault balances
  src/indexers/indexer.utils.ts
Labels: bug

#1106 fix: set available on dto
  package.json
  src/vaults/vaults.controller.spec.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
Labels: bug

#1107 fix: available balance on snapshot read
  package.json
  src/vaults/vaults.controller.spec.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
Labels: bug

#1108 chore: add crypto factory query
  src/protocols/strategies/convex.strategy.ts
Labels: enhancement

#1110 feat: oxd ecosystem vaults
  src/chains/config/fantom.config.ts
  src/config/tokens.config.ts
  src/metrics/__snapshots__/metrics.utils.spec.ts.snap
  src/tokens/config/fantom-tokens.config.ts
Labels: enhancement
