Repository Badger-Finance/badger-api, pull requests merged in 2022-08, with the labels that each got.

#1379 feat: add pinpoint harvest calculations
  package.json
  src/aws/models/vault-pending-harvest.model.ts
  src/indexers/indexer.utils.ts
  src/indexers/vault-harvests-indexer.ts
  src/indexers/vault-snapshots-indexer.spec.ts
  src/utils/discord.utils.spec.ts
  src/utils/discord.utils.ts
  src/vaults/__snapshots__/vaults.v2.controller.spec.ts.snap
  src/vaults/__snapshots__/vaults.v3.controller.spec.ts.snap
  src/vaults/vaults.service.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
  src/vaults/vaults.v2.controller.spec.ts
  yarn.lock
Labels: enhancement

#1380 chore: removal citadel implementations
  serverless.yml
  src/CitadelControllerRegistry.ts
  src/Server.ts
  src/citadel/__snapshots__/citadel.controller.spec.ts.snap
  src/citadel/__snapshots__/citadel.utils.spec.ts.snap
  src/citadel/citadel.constants.ts
  src/citadel/citadel.controller.spec.ts
  src/citadel/citadel.controller.ts
  src/citadel/citadel.service.ts
  src/citadel/citadel.utils.spec.ts
  src/citadel/citadel.utils.ts
  src/citadel/config/citadel-treasury.config.ts
  src/citadel/destructors/citadel-data.destructor.ts
  src/citadel/destructors/citadel-reward-event.destructor.ts
  src/citadel/interfaces/citadel-account.interface.ts
  src/citadel/interfaces/citadel-knights-round-stat.interface.ts
  src/citadel/interfaces/citadel-reward-event-model.interface.ts
  src/citadel/interfaces/citadel-reward-event.interface.ts
  src/citadel/interfaces/citadel-rewards-apr-blob.interface.ts
  src/citadel/interfaces/citadel-rewards-token-paid-map.interface.ts
  src/citadel/interfaces/citadel-summary-model.interface.ts
  src/citadel/interfaces/citadel-treasury-summary-model.interface.ts
  src/citadel/interfaces/get-list-rewards-options.interface.ts
  src/citadel/mocks/citadel-chart-data-blob.model.mock.ts
  src/citadel/mocks/citadel-list-rewards.sdk.mock.ts
  src/citadel/mocks/knighting-round-knight.graph.mock.ts
  src/citadel/mocks/query-citadel-data.util.mock.ts
  src/citadel/mocks/query-treasury-summary.util.mock.ts
  src/citadel/mocks/rewards-snapshot.model.mock.ts
  src/indexers/citadel-indexer.ts
  src/indexers/citadel-rewards-indexer.ts
  src/prices/__snapshots__/prices.controller.spec.ts.snap
  src/prices/__snapshots__/prices.service.spec.ts.snap
  src/tokens/config/eth-tokens.config.ts
Labels: enhancement

#1383 fix: resolve list aliasing issue
  src/vaults/__snapshots__/vaults.v2.controller.spec.ts.snap
  src/vaults/__snapshots__/vaults.v3.controller.spec.ts.snap
  src/vaults/vaults.service.ts
Labels: bug

#1386 chore: remove remaining treasury artifacts
  serverless.yml
  src/accounts/accounts.utils.spec.ts
  src/accounts/accounts.utils.ts
  src/aws/models/historic-treasury-summary-snapshot.model.ts
  src/aws/models/treasury-summary-snapshot.model.ts
  src/config/constants.ts
  src/treasury/examples/treasury-summary.mock.ts
  src/treasury/interfaces/cached-treasury-position.ts
  src/treasury/interfaces/treasury-summary.interface.ts
  src/treasury/interfaces/treasy-position.interface.ts
  src/treasury/treasury.service.ts
  src/treasury/treasury.utils.ts
Labels: enhancement

#1387 chore: update definitions table
  serverless.yml
  src/aws/models/vault-definition.model.ts
  src/config/constants.ts
  src/indexers/vault-definition-indexer.ts
Labels: bug

#1388 chore: update query req
  src/chains/vaults/chain.vaults.ts
Labels: bug

#1391 chore: update timer
  serverless.yml
  src/indexers/indexer.utils.ts
Labels: bug

#1392 feat: estimated yield fee scaling
  src/indexers/vault-harvests-indexer.ts
Labels: enhancement

#1394 chore: disable balancer fees
  src/protocols/strategies/balancer.strategy.ts
Labels: enhancement

#1395 fix: patch default indexer values
  src/aws/models/vault-pending-harvest.model.ts
  src/indexers/vault-harvests-indexer.ts
Labels: bug

#1396 fix: indexer patch
  src/aws/models/vault-pending-harvest.model.ts
  src/indexers/vault-harvests-indexer.ts
Labels: bug

#1398 fix: update from balancer feedback
  src/protocols/strategies/balancer.strategy.ts
Labels: enhancement

#1401 fix: filter only compound sources
  src/rewards/enums/source-type.enum.ts
  src/vaults/__snapshots__/vaults.utils.spec.ts.snap
  src/vaults/vaults.service.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
Labels: bug

#1402 fix: write filter function
  src/vaults/vaults.service.ts
  src/vaults/vaults.utils.ts
Labels: bug

#1403 fix: utilize token emission utility function
  src/chains/vaults/chain.vaults.ts
  src/indexers/apy-snapshots-indexer.ts
  src/indexers/vault-balances-indexer.ts
  src/protocols/strategies/convex.strategy.ts
  src/vaults/__snapshots__/vaults.utils.spec.ts.snap
  src/vaults/vaults.utils.ts
Labels: bug

#1405 chore: migration completion attempt
  serverless.yml
Labels: bug

#1404 release: vault api patch fixes
  serverless.yml
  src/chains/vaults/chain.vaults.ts
  src/indexers/apy-snapshots-indexer.ts
  src/indexers/vault-balances-indexer.ts
  src/migrations/historic-vault-migration.ts
  src/migrations/migration.utils.ts
  src/protocols/strategies/balancer.strategy.ts
  src/protocols/strategies/convex.strategy.ts
  src/rewards/enums/source-type.enum.ts
  src/vaults/__snapshots__/vaults.utils.spec.ts.snap
  src/vaults/vaults.service.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
Labels: bug, enhancement

#1407 chore: remove migration infra
  serverless.yml
  src/aws/interfaces/vault-definition-model.interface.ts
  src/aws/models/migration-process.model.ts
  src/aws/models/vault-definition.model.ts
  src/config/constants.ts
  src/indexers/indexer.utils.ts
  src/indexers/vaults-indexer.ts
  src/migrations/historic-vault-migration.ts
  src/migrations/migration.constants.ts
  src/migrations/migration.enums.ts
  src/migrations/migration.utils.ts
  src/test/constants.ts
Labels: enhancement

#1410 chore: migration removal into staging
  serverless.yml
  src/aws/interfaces/vault-definition-model.interface.ts
  src/aws/models/migration-process.model.ts
  src/aws/models/vault-definition.model.ts
  src/config/constants.ts
  src/indexers/indexer.utils.ts
  src/indexers/vaults-indexer.ts
  src/migrations/historic-vault-migration.ts
  src/migrations/migration.constants.ts
  src/migrations/migration.enums.ts
  src/migrations/migration.utils.ts
  src/test/constants.ts
Labels: enhancement

#1409 chore: value sources cleanup
  package.json
  seed/value-sources.json
  serverless.yml
  src/accounts/accounts.utils.ts
  src/aws/models/apy-snapshots.model.ts
  src/aws/models/current-vault-snapshot.model.ts
  src/aws/models/yield-source.model.ts
  src/charts/charts.utils.ts
  src/config/constants.ts
  src/indexers/apy-snapshots-indexer.spec.ts
  src/indexers/apy-snapshots-indexer.ts
  src/indexers/indexer.utils.ts
  src/indexers/vault-harvests-indexer.ts
  src/indexers/vault-snapshots-indexer.spec.ts
  src/indexers/vault-snapshots-indexer.ts
  src/indexers/vaults-indexer.spec.ts
  src/indexers/vaults-indexer.ts
  src/protocols/interfaces/value-source-map.interface.ts
  src/protocols/interfaces/value-source.interface.ts
  src/protocols/strategies/balancer.strategy.ts
  src/protocols/strategies/convex.strategy.ts
  src/protocols/strategies/oxdao.strategy.ts
  src/protocols/strategies/quickswap.strategy.ts
  src/protocols/strategies/strategy.utils.ts
  src/protocols/strategies/sushiswap.strategy.ts
  src/protocols/strategies/swapr.strategy.ts
  src/protocols/strategies/uniswap.strategy.ts
  src/rewards/enums/source-type.enum.ts
  src/rewards/rewards.utils.ts
  src/test/constants.ts
  src/test/tests.utils.ts
  src/tokens/__snapshots__/tokens.utils.spec.ts.snap
  src/tokens/mocks/full-token.mock.ts
  src/tokens/tokens.utils.spec.ts
  src/tokens/tokens.utils.ts
  src/vaults/__snapshots__/vaults.utils.spec.ts.snap
  src/vaults/__snapshots__/vaults.v2.controller.spec.ts.snap
  src/vaults/__snapshots__/vaults.v3.controller.spec.ts.snap
  src/vaults/interfaces/vault-model.interface.ts
  src/vaults/interfaces/yield-sources.interface.ts
  src/vaults/setts.v2.controller.ts
  src/vaults/vaults.service.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
  src/vaults/vaults.v2.controller.spec.ts
  src/vaults/vaults.v2.controller.ts
  src/vaults/vaults.v3.controller.spec.ts
  src/vaults/vaults.v3.controller.ts
  src/vaults/yields.utils.spec.ts
  src/vaults/yields.utils.ts
  yarn.lock
Labels: enhancement

#1411 chore: remove indexer job
  serverless.yml
Labels: enhancement

#1412 chore: table name update
  serverless.yml
Labels: bug

#1413 chore: update deploy
  .github/workflows/deploy.yml
Labels: bug

#1414 fix: prayger resolve deps
  .github/workflows/deploy.yml
  package.json
  src/indexers/vault-snapshots-indexer.spec.ts
  src/indexers/vault-snapshots-indexer.ts
  yarn.lock
Labels: bug

#1415 fix: rever deploy change
  .github/workflows/deploy.yml
Labels: enhancement

#1416 chore: update dev dep
  package.json
  yarn.lock
Labels: bug

#1417 chore: revert full token changs
  .github/workflows/deploy.yml
  package.json
  src/tokens/mocks/full-token.mock.ts
  src/vaults/__snapshots__/vaults.utils.spec.ts.snap
  src/vaults/interfaces/vault-model.interface.ts
Labels: bug

#1418 chore: update min max calcs
  src/indexers/vault-balances-indexer.ts
  src/tokens/mocks/full-token.mock.ts
  src/vaults/__snapshots__/vaults.v2.controller.spec.ts.snap
  src/vaults/__snapshots__/vaults.v3.controller.spec.ts.snap
  src/vaults/vaults.service.ts
Labels: bug

#1419 test: vaults yield utils coverage
  package.json
  src/ControllerRegistry.ts
  src/indexers/indexer.utils.ts
  src/test/constants.ts
  src/test/tests.utils.ts
  src/vaults/__snapshots__/yields.utils.spec.ts.snap
  src/vaults/interfaces/vault-model.interface.ts
  src/vaults/setts.v2.controller.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
  src/vaults/yields.utils.spec.ts
  src/vaults/yields.utils.ts
  yarn.lock
Labels: enhancement

#1420 chore: add harvest apr alert + avoidance
  serverless.yml
  src/aws/models/yield-estimate.model.ts
  src/config/constants.ts
  src/indexers/vault-harvests-indexer.ts
  src/vaults/vaults.service.ts
  src/vaults/vaults.utils.ts
  src/vaults/vaults.v2.controller.spec.ts
  src/vaults/yields.utils.ts
Labels: bug

#1421 feat: add optimism support
  serverless.yml
  src/ControllerRegistry.ts
  src/accounts/accounts.utils.ts
  src/chains/chain.ts
  src/chains/config/arbitrum.config.ts
  src/chains/config/bsc.config.ts
  src/chains/config/chain.config.ts
  src/chains/config/eth.config.ts
  src/chains/config/fantom.config.ts
  src/chains/config/optimism.config.ts
  src/chains/config/polygon.config.ts
  src/chains/enums/provider.enum.ts
  src/config/rpc.config.ts
  src/dev/dev.utils.ts
  src/gas/__snapshots__/gas.utils.spec.ts.snap
  src/indexers/accounts-indexer.ts
  src/indexers/apy-snapshots-indexer.ts
  src/indexers/indexer.utils.ts
  src/indexers/vault-definition-indexer.ts
  src/indexers/yield-estimates-indexer.ts
  src/metrics/__snapshots__/metrics.utils.spec.ts.snap
  src/proofs/__snapshots__/proof.v3.controller.spec.ts.snap
  src/proofs/__snapshots__/proofs.v2.controller.spec.ts.snap
  src/proofs/proof.v3.controller.spec.ts
  src/proofs/proofs.service.spec.ts
  src/proofs/proofs.service.ts
  src/proofs/proofs.v2.controller.spec.ts
  src/rewards/rewards.service.spec.ts
  src/rewards/rewards.service.ts
  src/rewards/rewards.utils.ts
  src/test/constants.ts
  src/test/tests.utils.ts
  src/vaults/vaults.service.ts
  src/vaults/yields.utils.ts
Labels: enhancement

#1422 test: add projected yield coverage
  src/vaults/__snapshots__/yields.utils.spec.ts.snap
  src/vaults/yields.utils.spec.ts
Labels: test

#1423 fix: timestamp query expansion
  src/accounts/__snapshots__/account.v3.controller.spec.ts.snap
  src/accounts/__snapshots__/accounts.service.spec.ts.snap
  src/accounts/__snapshots__/accounts.v2.controller.spec.ts.snap
  src/accounts/account.v3.controller.spec.ts
  src/accounts/accounts.service.spec.ts
  src/accounts/accounts.utils.spec.ts
  src/accounts/accounts.v2.controller.spec.ts
  src/aws/dynamodb.utils.ts
  src/aws/interfaces/chainish.interface.ts
  src/aws/interfaces/vaultish.interface.ts
  src/aws/models/historic-vault-snapshot.model.ts
  src/charts/__snapshots__/charts.controller.spec.ts.snap
  src/charts/charts.controller.spec.ts
  src/charts/charts.utils.ts
  src/indexers/indexer.utils.ts
  src/indexers/vault-definition-indexer.ts
  src/indexers/vault-snapshots-indexer.ts
  src/proofs/__snapshots__/proof.v3.controller.spec.ts.snap
  src/proofs/__snapshots__/proofs.service.spec.ts.snap
  src/proofs/__snapshots__/proofs.v2.controller.spec.ts.snap
  src/proofs/proof.v3.controller.spec.ts
  src/proofs/proofs.service.spec.ts
  src/proofs/proofs.v2.controller.spec.ts
  src/rewards/rewards.service.spec.ts
  src/test/constants.ts
  src/test/tests.utils.ts
  src/vaults/__snapshots__/vaults.v3.controller.spec.ts.snap
  src/vaults/mocks/historic-vault-snapshots.mock.ts
  src/vaults/vaults.service.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.v3.controller.spec.ts
  src/vaults/vaults.v3.controller.ts
Labels: bug

#1426 feat: upd badger sdk, use only registryV2
  package.json
  src/dev/dev.utils.ts
  src/indexers/vault-definition-indexer.ts
  src/vaults/vaults.utils.ts
  yarn.lock
Labels: enhancement

#1425 fix: update bvecvx sourcing, remove type causing bad look ups
  seed/vault-snapshots.json
  src/aws/models/yield-source.model.ts
  src/protocols/strategies/convex.strategy.ts
  src/vaults/vaults.utils.ts
  src/vaults/yields.utils.ts
Labels: bug

#1427 fix: address issue leaving boost as enabled
  src/vaults/vaults.service.ts
  src/vaults/vaults.v3.controller.ts
Labels: bug

#1428 fix: previously boosted vaults
  src/vaults/vaults.service.ts
  src/vaults/vaults.v3.controller.ts
Labels: bug

#1429 chore: update charting endpoints + tests
  src/accounts/account.v3.controller.spec.ts
  src/aws/models/historic-vault-snapshot-old.model.ts
  src/charts/__snapshots__/charts.controller.spec.ts.snap
  src/charts/__snapshots__/charts.service.spec.ts.snap
  src/charts/charts.controller.spec.ts
  src/charts/charts.controller.ts
  src/charts/charts.service.spec.ts
  src/charts/charts.service.ts
  src/charts/charts.utils.ts
  src/charts/dto/charts-query.dto.ts
  src/charts/enums/chart-granularity.enum.ts
  src/errors/access/base.access.denied.error.ts
  src/errors/allocation/not.found.error.ts
  src/errors/base.error.ts
  src/errors/enums/network-status.enum.ts
  src/errors/validation/base.validation.error.ts
  src/proofs/proof.v3.controller.spec.ts
  src/rewards/rewards.v3.controller.spec.ts
  src/test/constants.ts
  src/vaults/vaults.service.ts
  src/vaults/vaults.utils.ts
  src/vaults/vaults.v3.controller.spec.ts
Labels: enhancement

#1430 chore: library upgrades
  package.json
  yarn.lock
Labels: enhancement

#1431 release: chart api removal
  package.json
  src/accounts/account.v3.controller.spec.ts
  src/aws/models/historic-vault-snapshot-old.model.ts
  src/charts/__snapshots__/charts.controller.spec.ts.snap
  src/charts/__snapshots__/charts.service.spec.ts.snap
  src/charts/charts.controller.spec.ts
  src/charts/charts.controller.ts
  src/charts/charts.service.spec.ts
  src/charts/charts.service.ts
  src/charts/charts.utils.ts
  src/charts/dto/charts-query.dto.ts
  src/charts/enums/chart-granularity.enum.ts
  src/errors/access/base.access.denied.error.ts
  src/errors/allocation/not.found.error.ts
  src/errors/base.error.ts
  src/errors/enums/network-status.enum.ts
  src/errors/validation/base.validation.error.ts
  src/proofs/proof.v3.controller.spec.ts
  src/rewards/rewards.v3.controller.spec.ts
  src/test/constants.ts
  src/vaults/vaults.service.ts
  src/vaults/vaults.utils.ts
  src/vaults/vaults.v3.controller.spec.ts
  yarn.lock
Labels: enhancement

#1432 chore: remove old chart infra + data
  serverless.yml
  src/config/constants.ts
Labels: enhancement

#1433 fix: revert table removal
  serverless.yml
Labels: bug

#1434 fix: calculate yield check
  src/vaults/yields.utils.spec.ts
  src/vaults/yields.utils.ts
Labels: bug

#1435 release: chart infra removals + yield calc fix
  serverless.yml
  src/config/constants.ts
  src/vaults/yields.utils.spec.ts
  src/vaults/yields.utils.ts
Labels: bug, enhancement

#1439 tests: follow up for vault definition
  src/indexers/vault-definition-indexer.spec.ts
  src/indexers/vault-definition-indexer.ts
  src/test/tests.utils.ts
Labels: test

#1442 release: graviaura yield fix + vault defs testing
  src/contracts/factories/index.ts
  src/indexers/vault-definition-indexer.spec.ts
  src/indexers/vault-definition-indexer.ts
  src/test/tests.utils.ts
  src/vaults/vaults.utils.ts
  src/vaults/yields.config.ts
Labels: bug

#1444 fix: update target block picking
  src/vaults/vaults.utils.ts
Labels: bug

#1445 release: block logic update
  serverless_frontend.yml
  src/vaults/vaults.utils.ts
Labels: bug

#1447 chore: remove clean modules
  .github/workflows/deploy.yml
Labels: enhancement

#1446 tests: indexer utils
  package.json
  src/chains/config/test.config.ts
  src/indexers/__snapshots__/indexer.utils.spec.ts.snap
  src/indexers/indexer.utils.spec.ts
  src/test/constants.ts
  src/test/mocks.utils.ts
  src/test/tests.utils.ts
Labels: test

#1451 chore: update graviaura yield weight
  serverless.yml
  src/protocols/strategies/balancer.strategy.ts
  src/vaults/influence.utils.ts
  src/vaults/vaults.utils.ts
  src/vaults/yields.config.ts
Labels: bug, enhancement

#1455 chore: update rewards code
  package.json
  src/accounts/accounts.utils.ts
  src/indexers/vault-definition-indexer.spec.ts
  src/vaults/__snapshots__/vaults.utils.spec.ts.snap
  src/vaults/influence.utils.ts
  src/vaults/vaults.utils.ts
  yarn.lock
Labels: enhancement

#1463 fix: initial yield path simplification test updates
  .eslintignore
  jest.config.ts
  package.json
  serverless_frontend.yml
  src/accounts/accounts.utils.spec.ts
  src/chains/chain.ts
  src/chains/chains.utils.ts
  src/dev/dev.utils.ts
  src/indexers/__snapshots__/indexer.utils.spec.ts.snap
  src/indexers/accounts-indexer.ts
  src/indexers/apy-snapshots-indexer.spec.ts
  src/indexers/apy-snapshots-indexer.ts
  src/indexers/harvest-compound-indexer.spec.ts
  src/indexers/harvest-compound-indexer.ts
  src/indexers/leaderboard-indexer.spec.ts
  src/indexers/leaderboard-indexer.ts
  src/indexers/prices-indexer.ts
  src/indexers/protocol-metric-indexer.ts
  src/indexers/vault-balances-indexer.ts
  src/indexers/vault-definition-indexer.spec.ts
  src/indexers/vault-definition-indexer.ts
  src/indexers/vault-snapshots-indexer.spec.ts
  src/indexers/vault-snapshots-indexer.ts
  src/indexers/yield-estimates-indexer.ts
  src/prices/prices.utils.ts
  src/rewards/rewards.utils.ts
  src/test/jest.setup.ts
  src/test/mocks.utils.ts
  src/test/tests.utils.ts
  src/vaults/__snapshots__/harvests.utils.spec.ts.snap
  src/vaults/__snapshots__/vaults.utils.spec.ts.snap
  src/vaults/harvests.utils.spec.ts
  src/vaults/harvests.utils.ts
  src/vaults/influence.utils.ts
  src/vaults/interfaces/vault-performance-item.interface.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
  src/vaults/yields.utils.ts
  yarn.lock
Labels: enhancement

#1466 chore: utilize token emitted values at snapshot time
  src/accounts/accounts.v2.controller.ts
  src/accounts/accounts.v3.controller.ts
  src/chains/chains.utils.ts
  src/chains/strategies/base.strategy.ts
  src/charts/charts.controller.ts
  src/gas/gas.controller.ts
  src/leaderboards/leaderboards.controller.ts
  src/prices/prices.controller.spec.ts
  src/prices/prices.controller.ts
  src/proofs/proofs.v2.controller.ts
  src/proofs/proofs.v3.controller.ts
  src/protocols/protocols.controller.ts
  src/protocols/strategies/balancer.strategy.ts
  src/rewards/__snapshots__/reward.v2.controller.spec.ts.snap
  src/rewards/reward.v2.controller.spec.ts
  src/rewards/reward.v2.controller.ts
  src/rewards/rewards.v3.controller.ts
  src/test/mocks.utils.ts
  src/tokens/tokens.controller.ts
  src/vaults/vaults.utils.ts
  src/vaults/vaults.v2.controller.spec.ts
  src/vaults/vaults.v2.controller.ts
  src/vaults/vaults.v3.controller.spec.ts
  src/vaults/vaults.v3.controller.ts
  src/vaults/yields.utils.ts
Labels: enhancement

#1467 fix: update compound apr input values
  serverless.yml
  src/vaults/interfaces/harvest-report.interface.ts
  src/vaults/yields.utils.ts
Labels: bug, enhancement

#1471 chore: fix liquidity for bveoxd + convex
  src/protocols/strategies/convex.strategy.ts
  src/protocols/strategies/oxdao.strategy.ts
  src/vaults/interfaces/harvest-report.interface.ts
  src/vaults/yields.utils.ts
Labels: bug

#1472 chore: additions for vaults coverages
  jest.config.ts
  src/indexers/yield-estimates-indexer.ts
  src/test/constants.ts
  src/tokens/tokens.utils.spec.ts
  src/tokens/tokens.utils.ts
  src/vaults/vaults.config.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
  src/vaults/vaults.v2.controller.spec.ts
  src/vaults/yields.utils.spec.ts
  src/vaults/yields.utils.ts
Labels: test

#1473 chore: add documentation to methods + refactor evaluation methods
  src/indexers/vault-balances-indexer.spec.ts
  src/metrics/__snapshots__/metrics.utils.spec.ts.snap
  src/metrics/metrics.utils.spec.ts
  src/vaults/interfaces/harvest-report.interface.ts
  src/vaults/interfaces/vault-yield-summary.interface.ts
  src/vaults/vaults.config.ts
  src/vaults/yields.utils.ts
Labels: documentation, test

#1474 chore: update yield period
  src/indexers/yield-estimates-indexer.ts
  src/vaults/vaults.config.ts
Labels: bug

#1475 chore: emission control removal + initial yields coverages
  README.md
  docs/images/badger_warlock.png
  package.json
  src/abi/emission-control.abi
  src/chains/config/arbitrum.config.ts
  src/chains/config/chain.config.ts
  src/chains/config/eth.config.ts
  src/chains/config/fantom.config.ts
  src/chains/config/test.config.ts
  src/contracts/index.ts
  src/indexers/__snapshots__/indexer.utils.spec.ts.snap
  src/indexers/indexer.utils.spec.ts
  src/indexers/indexer.utils.ts
  src/test/constants.ts
  src/test/mocks.utils/contracts/mock.contract.base.ts
  src/test/mocks.utils/dynamo.db/mock.calls.ts
  src/test/mocks.utils/mock.api.chain.ts
  src/vaults/__snapshots__/yields.utils.spec.ts.snap
  src/vaults/vaults.config.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
  src/vaults/yields.utils.spec.ts
  src/vaults/yields.utils.ts
  tsconfig.build.json
  yarn.lock
Labels: test

#1477 fix: bveCVX filtered events for voting rounds
  src/abi/cvx-locker.abi
  src/contracts/CvxLocker.ts
  src/contracts/factories/CvxLocker__factory.ts
  src/contracts/index.ts
  src/protocols/strategies/convex.strategy.ts
  src/vaults/influence.utils.ts
  src/vaults/yields.utils.ts
Labels: enhancement

#1478 release: general apr fixes + bvecvx voting round fix
  README.md
  docs/images/badger_warlock.png
  jest.config.ts
  package.json
  src/abi/cvx-locker.abi
  src/abi/emission-control.abi
  src/chains/config/arbitrum.config.ts
  src/chains/config/chain.config.ts
  src/chains/config/eth.config.ts
  src/chains/config/fantom.config.ts
  src/chains/config/test.config.ts
  src/contracts/CvxLocker.ts
  src/contracts/factories/CvxLocker__factory.ts
  src/contracts/index.ts
  src/indexers/__snapshots__/indexer.utils.spec.ts.snap
  src/indexers/indexer.utils.spec.ts
  src/indexers/indexer.utils.ts
  src/indexers/vault-balances-indexer.spec.ts
  src/indexers/yield-estimates-indexer.ts
  src/metrics/__snapshots__/metrics.utils.spec.ts.snap
  src/metrics/metrics.utils.spec.ts
  src/protocols/strategies/convex.strategy.ts
  src/protocols/strategies/oxdao.strategy.ts
  src/test/constants.ts
  src/test/mocks.utils/contracts/mock.contract.base.ts
  src/test/mocks.utils/dynamo.db/mock.calls.ts
  src/test/mocks.utils/index.ts
  src/test/mocks.utils/mock.api.chain.ts
  src/test/mocks.utils/mock.badger.sdk.ts
  src/tokens/tokens.utils.spec.ts
  src/tokens/tokens.utils.ts
  src/vaults/__snapshots__/yields.utils.spec.ts.snap
  src/vaults/influence.utils.ts
  src/vaults/interfaces/harvest-report.interface.ts
  src/vaults/interfaces/vault-yield-summary.interface.ts
  src/vaults/vaults.config.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
  src/vaults/vaults.v2.controller.spec.ts
  src/vaults/yields.utils.spec.ts
  src/vaults/yields.utils.ts
  tsconfig.build.json
  yarn.lock
Labels: bug, enhancement

#1480 fix: disable temporarily vault warning
  src/indexers/yield-estimates-indexer.ts
Labels: bug

#1481 fix: update flywheel inputs
  src/vaults/yields.utils.ts
Labels: bug

#1482 fix: flywheel apr inputs
  src/vaults/yields.utils.ts
Labels: bug

#1483 chore: minor indexer clean ups + logging, update sdk version
  package.json
  src/indexers/yield-estimates-indexer.ts
  src/tokens/tokens.utils.ts
  yarn.lock
Labels: bug

#1484 test: add vault flywheel test path
  src/vaults/__snapshots__/yields.utils.spec.ts.snap
  src/vaults/yields.utils.spec.ts
Labels: test

#1485 release: sdk upgrade fix
  package.json
  src/indexers/yield-estimates-indexer.ts
  src/tokens/tokens.utils.ts
  src/vaults/__snapshots__/yields.utils.spec.ts.snap
  src/vaults/yields.utils.spec.ts
  yarn.lock
Labels: bug

#1486 test: add graph path tests
  src/test/constants.ts
  src/vaults/__snapshots__/yields.utils.spec.ts.snap
  src/vaults/yields.utils.spec.ts
Labels: test

#1487 test: add metrics query coverage
  jest.config.ts
  src/aws/models/protocol-metric-snapshot.model.ts
  src/metrics/interfaces/metrics.interface.ts
  src/metrics/interfaces/protocol-metric-model.ts
  src/metrics/metrics.controller.spec.ts
  src/metrics/metrics.controller.ts
  src/metrics/metrics.service.ts
  src/metrics/metrics.utils.spec.ts
  src/metrics/metrics.utils.ts
  src/test/constants.ts
Labels: test

#1489 feat: indexer yield projections
  src/accounts/accounts.utils.ts
  src/aws/models/cached-account.model.ts
  src/aws/models/cached-sett-balance.interface.ts
  src/aws/models/cached-token-balance.interface.ts
  src/aws/models/cached-token-rate.interface.ts
  src/aws/models/cached-yield-projection.model.ts
  src/aws/models/cached-yield-source.interface.ts
  src/aws/models/vault-token-balance.model.ts
  src/aws/models/yield-estimate.model.ts
  src/aws/models/yield-source.model.ts
  src/config/constants.ts
  src/indexers/yield-estimates-indexer.ts
  src/metrics/__snapshots__/metrics.controller.spec.ts.snap
  src/metrics/metrics.controller.spec.ts
  src/protocols/strategies/balancer.strategy.ts
  src/protocols/strategies/convex.strategy.ts
  src/tokens/destructors/token.destructor.ts
  src/tokens/interfaces/mbstable-api-response.interface.ts
  src/tokens/tokens.utils.ts
  src/vaults/__snapshots__/vaults.v2.controller.spec.ts.snap
  src/vaults/__snapshots__/vaults.v3.controller.spec.ts.snap
  src/vaults/vaults.service.ts
  src/vaults/vaults.utils.ts
  src/vaults/vaults.v2.controller.spec.ts
  src/vaults/yields.utils.ts
Labels: enhancement

#1491 fix: add projections infra
  serverless.yml
Labels: bug

#1490 fix: yield estimate indexer migration
  jest.config.ts
  serverless.yml
  src/accounts/accounts.utils.ts
  src/aws/models/cached-account.model.ts
  src/aws/models/cached-sett-balance.interface.ts
  src/aws/models/cached-token-balance.interface.ts
  src/aws/models/cached-token-rate.interface.ts
  src/aws/models/cached-yield-projection.model.ts
  src/aws/models/cached-yield-source.interface.ts
  src/aws/models/protocol-metric-snapshot.model.ts
  src/aws/models/vault-token-balance.model.ts
  src/aws/models/yield-estimate.model.ts
  src/aws/models/yield-source.model.ts
  src/config/constants.ts
  src/indexers/yield-estimates-indexer.ts
  src/metrics/__snapshots__/metrics.controller.spec.ts.snap
  src/metrics/interfaces/metrics.interface.ts
  src/metrics/interfaces/protocol-metric-model.ts
  src/metrics/metrics.controller.spec.ts
  src/metrics/metrics.controller.ts
  src/metrics/metrics.service.ts
  src/metrics/metrics.utils.spec.ts
  src/metrics/metrics.utils.ts
  src/protocols/strategies/balancer.strategy.ts
  src/protocols/strategies/convex.strategy.ts
  src/test/constants.ts
  src/tokens/destructors/token.destructor.ts
  src/tokens/interfaces/mbstable-api-response.interface.ts
  src/tokens/tokens.utils.ts
  src/vaults/__snapshots__/vaults.v2.controller.spec.ts.snap
  src/vaults/__snapshots__/vaults.v3.controller.spec.ts.snap
  src/vaults/__snapshots__/yields.utils.spec.ts.snap
  src/vaults/vaults.service.ts
  src/vaults/vaults.utils.ts
  src/vaults/vaults.v2.controller.spec.ts
  src/vaults/yields.utils.spec.ts
  src/vaults/yields.utils.ts
Labels: bug

#1492 fix: dynamodb mapper embed type
  src/aws/models/cached-yield-projection.model.ts
  src/aws/models/cached-yield-source.interface.ts
  src/chains/chains.utils.ts
  src/indexers/vault-definition-indexer.ts
  src/indexers/yield-estimates-indexer.ts
  src/vaults/yields.utils.ts
Labels: bug

#1493 fix: dynamodb mapper embed type
  src/aws/models/cached-yield-projection.model.ts
  src/aws/models/cached-yield-source.interface.ts
  src/chains/chains.utils.ts
  src/indexers/vault-definition-indexer.ts
  src/indexers/yield-estimates-indexer.ts
  src/vaults/yields.utils.ts
Labels: bug

#1495 chore: apply broad filtering rules
  src/vaults/influence.utils.ts
Labels: enhancement

#1496 release: influence vault filtering
  src/vaults/influence.utils.ts
Labels: enhancement

#1500 feat: yield event core infrastructure
  package.json
  serverless.yml
  serverless_frontend.yml
  src/aws/models/cached-leaderboard-summary.model.ts
  src/aws/models/harvest-compound.model.ts
  src/aws/models/vault-yield-event.model.ts
  src/config/constants.ts
  src/indexers/harvest-compound-indexer.spec.ts
  src/indexers/harvest-compound-indexer.ts
  src/indexers/vault-harvests-indexer.spec.ts
  src/indexers/vault-harvests-indexer.ts
  src/leaderboards/interface/leaderboard-data-model.interrface.ts
  src/leaderboards/interface/leaderboard-rank-summary.interface.ts
  src/test/constants.ts
  src/test/mocks.utils/mock.api.chain.ts
  src/vaults/__snapshots__/harvests.utils.spec.ts.snap
  src/vaults/__snapshots__/vaults.utils.spec.ts.snap
  src/vaults/__snapshots__/vaults.v2.controller.spec.ts.snap
  src/vaults/__snapshots__/vaults.v3.controller.spec.ts.snap
  src/vaults/__snapshots__/yields.utils.spec.ts.snap
  src/vaults/enums/yield-type.enum.ts
  src/vaults/harvests.utils.spec.ts
  src/vaults/harvests.utils.ts
  src/vaults/influence.utils.ts
  src/vaults/interfaces/harvest-report.interface.ts
  src/vaults/interfaces/vault-harvest-extended.interface.ts
  src/vaults/interfaces/vault-harvests-model.interface.ts
  src/vaults/interfaces/vault-performance-item.interface.ts
  src/vaults/interfaces/vault-yield-item.interface.ts
  src/vaults/interfaces/yield-event.ts
  src/vaults/mocks/vault-harvests-on-chain.ts
  src/vaults/mocks/vaults-harvests-map.mock.ts
  src/vaults/vaults.service.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
  src/vaults/vaults.v2.controller.ts
  src/vaults/vaults.v3.controller.spec.ts
  src/vaults/vaults.v3.controller.ts
  src/vaults/yields.utils.spec.ts
  src/vaults/yields.utils.ts
Labels: enhancement

#1502 fix: update sls table name
  serverless.yml
  serverless_frontend.yml
Labels: bug

#1503 chore: add end block, fix new acc deploy
  serverless.yml
  serverless_frontend.yml
  src/indexers/vault-harvests-indexer.ts
  src/vaults/harvests.utils.ts
Labels: bug

#1505 fix: update vault event indexing logic
  serverless.yml
  serverless_frontend.yml
  src/indexers/vault-harvests-indexer.ts
  src/vaults/harvests.utils.spec.ts
  src/vaults/harvests.utils.ts
Labels: enhancement
