Repository Badger-Finance/badger-api, pull requests merged in 2022-02, with the labels that each got.

#899 chore: add codeql analysis gha
  .github/workflows/codeql-analysis.yml
Labels: enhancement

#900 release: codeql addition
  .github/workflows/codeql-analysis.yml
Labels: enhancement

#902 chore: add fantom vault, tokens pricing
  src/abi/solidly-pair.abi
  src/chains/chain.ts
  src/chains/config/fantom.config.ts
  src/chains/strategies/fantom.strategy.ts
  src/config/tokens.config.ts
  src/contracts/SolidlyPair.d.ts
  src/contracts/factories/SolidlyPair__factory.ts
  src/contracts/index.ts
  src/prices/prices.controller.ts
  src/protocols/common/swap.utils.ts
  src/test/tests.utils.ts
  src/tokens/config/fantom-tokens.config.ts
  src/tokens/config/ftm-tokens.config.ts
  src/tokens/enums/token-type.enum.ts
  src/tokens/tokens.utils.ts
Labels: enhancement

#906 chore: update bcvxcrv strategy estimation
  src/protocols/strategies/convex.strategy.ts
  src/rewards/rewards.utils.ts
Labels: bug

#908 chore: update price seeds + introduce initial coingecko batching
  seed/prices.json
  seed/scripts/update-prices.ts
  src/chains/config/arbitrum.config.ts
  src/chains/config/bsc.config.ts
  src/chains/config/eth.config.ts
  src/chains/config/fantom.config.ts
  src/chains/config/matic.config.ts
  src/chains/config/xdai.config.ts
  src/chains/strategies/arbitrum.strategy.ts
  src/chains/strategies/base.strategy.ts
  src/chains/strategies/bsc.strategy.ts
  src/chains/strategies/chain.strategy.ts
  src/chains/strategies/eth.strategy.ts
  src/chains/strategies/fantom.strategy.ts
  src/chains/strategies/matic.strategy.ts
  src/chains/strategies/test.strategy.ts
  src/chains/strategies/xdai.strategy.ts
  src/config/tokens.config.ts
  src/prices/__snapshots__/prices.controller.spec.ts.snap
  src/prices/__snapshots__/prices.service.spec.ts.snap
  src/prices/custom/remdigg-price.ts
  src/prices/interface/coingecko-price-response.interface.ts
  src/prices/interface/token-price-snapshot.interface.ts
  src/prices/interface/token-price.interface.ts
  src/prices/prices.utils.spec.ts
  src/prices/prices.utils.ts
  src/protocols/common/swap.utils.ts
  src/protocols/strategies/convex.strategy.ts
  src/protocols/strategies/mstable.strategy.ts
  src/tokens/__snapshots__/tokens.controller.spec.ts.snap
  src/tokens/config/eth-tokens.config.ts
  src/tokens/interfaces/price-data.interface.ts
  src/tokens/interfaces/token.interface.ts
  src/tokens/tokens.utils.spec.ts
  src/vaults/vaults.utils.ts
  tsconfig.build.json
  tsconfig.json
Labels: enhancement

#911 chore: promote stable vaults
  src/chains/config/eth.config.ts
  src/vaults/__snapshots__/vaults.controller.spec.ts.snap
Labels: enhancement

#913 chore: add multichain base token currency conversions
  serverless.yml
  src/chains/config/polygon.config.ts
  src/config/tokens.config.ts
  src/prices/prices.utils.spec.ts
  src/prices/prices.utils.ts
  src/tokens/config/fantom-tokens.config.ts
  src/tokens/config/polygon-tokens.config.ts
  src/tokens/tokens.utils.ts
Labels: enhancement

#915 chore: clean up vault code + add vault pricing test cases
  src/charts/charts.service.ts
  src/indexers/indexer.utils.ts
  src/indexers/price-indexer.ts
  src/indexers/sett-snapshots-indexer.spec.ts
  src/rewards/rewards.utils.ts
  src/test/tests.utils.ts
  src/vaults/interfaces/cached-sett-snapshot.interface.ts
  src/vaults/vaults.service.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
Labels: bug

#916 release: pricing function fix
  src/charts/charts.service.ts
  src/indexers/indexer.utils.ts
  src/indexers/price-indexer.ts
  src/indexers/sett-snapshots-indexer.spec.ts
  src/rewards/rewards.utils.ts
  src/test/tests.utils.ts
  src/vaults/interfaces/cached-sett-snapshot.interface.ts
  src/vaults/vaults.service.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
Labels: bug

#917 chore: add bvecvx boost support
  package.json
  src/accounts/__snapshots__/accounts.controller.spec.ts.snap
  src/accounts/__snapshots__/accounts.service.spec.ts.snap
  src/accounts/accounts.controller.spec.ts
  src/accounts/accounts.service.spec.ts
  src/accounts/accounts.utils.spec.ts
  src/accounts/accounts.utils.ts
  src/accounts/interfaces/account-model.interface.ts
  src/indexers/boosts-indexer.spec.ts
  src/indexers/leaderboard-indexer.ts
  src/leaderboards/interface/cached-boost.interface.ts
  yarn.lock
Labels: enhancement

#918 release: bvecvx balance
  package.json
  src/accounts/__snapshots__/accounts.controller.spec.ts.snap
  src/accounts/__snapshots__/accounts.service.spec.ts.snap
  src/accounts/accounts.controller.spec.ts
  src/accounts/accounts.service.spec.ts
  src/accounts/accounts.utils.spec.ts
  src/accounts/accounts.utils.ts
  src/accounts/interfaces/account-model.interface.ts
  src/indexers/boosts-indexer.spec.ts
  src/indexers/leaderboard-indexer.ts
  src/leaderboards/interface/cached-boost.interface.ts
  yarn.lock
Labels: enhancement

#919 chore: add bad price remapping
  src/indexers/price-indexer.ts
  src/prices/prices.utils.ts
  src/protocols/strategies/mstable.strategy.ts
  src/vaults/vaults.utils.ts
Labels: bug

#921 feat: event based apr estimation
  package.json
  src/indexers/indexer.utils.ts
  src/indexers/price-indexer.ts
  src/indexers/sett-snapshots-indexer.spec.ts
  src/proofs/proofs.service.spec.ts
  src/protocols/protocols.utils.ts
  src/protocols/strategies/mstable.strategy.ts
  src/rewards/rewards.utils.ts
  src/test/tests.utils.ts
  src/vaults/__snapshots__/vaults.service.spec.ts.snap
  src/vaults/__snapshots__/vaults.utils.spec.ts.snap
  src/vaults/vaults.service.spec.ts
  src/vaults/vaults.service.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
  yarn.lock
Labels: enhancement

#923 fix: always include rewards emissions
  src/indexers/vault-snapshots-indexer.spec.ts
  src/indexers/vault-snapshots-indexer.ts
  src/protocols/common/swap.utils.ts
  src/rewards/rewards.utils.ts
  src/test/tests.utils.ts
  src/vaults/__snapshots__/vaults.utils.spec.ts.snap
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
Labels: bug

#924 chore: add new fantom vaults
  src/chains/config/fantom.config.ts
  src/config/tokens.config.ts
  src/tokens/config/fantom-tokens.config.ts
Labels: enhancement

#925 fix: vault snapshots event handler update
  serverless.yml
Labels: bug

#926 chore: revert arbitrum removals + add protocol fee apr
  src/protocols/strategies/convex.strategy.ts
  src/rewards/rewards.utils.ts
  src/vaults/__snapshots__/vaults.utils.spec.ts.snap
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
Labels: bug

#927 chore: remove usdc-dai + add pricing
  src/chains/config/fantom.config.ts
  src/config/tokens.config.ts
  src/rewards/rewards.utils.ts
  src/tokens/config/fantom-tokens.config.ts
Labels: enhancement

#929 fix: add spell token support
  seed/prices.json
  src/config/tokens.config.ts
  src/indexers/indexer.utils.ts
  src/prices/__snapshots__/prices.controller.spec.ts.snap
  src/prices/__snapshots__/prices.service.spec.ts.snap
  src/tokens/__snapshots__/tokens.controller.spec.ts.snap
  src/tokens/config/eth-tokens.config.ts
  src/tokens/tokens.utils.ts
  src/vaults/vaults.utils.ts
Labels: bug

#930 chore: add solid + sex tokens
  seed/prices.json
  src/chains/strategies/base.strategy.ts
  src/config/tokens.config.ts
  src/prices/enums/pricing-type.enum.ts
  src/protocols/common/swap.utils.ts
  src/tokens/config/fantom-tokens.config.ts
Labels: enhancement

#931 chore: fix swapr subgraph url + ignore spell emissions
  serverless.yml
  src/config/constants.ts
  src/protocols/strategies/convex.strategy.ts
  src/protocols/strategies/swapr.strategy.ts
Labels: bug

#932 chore: bump lambda memory + update delete request
  package.json
  serverless.yml
  src/rewards/rewards.utils.ts
  yarn.lock
Labels: bug

#934 chore: remove old unused health api
  src/ControllerRegistry.ts
  src/health/apis-health.service.ts
  src/health/contracts-health.service.ts
  src/health/health.config.ts
  src/health/health.controller.ts
  src/health/health.interface.ts
  src/health/health.service.spec.ts
  src/health/health.types.ts
  src/health/health.utils.ts
  src/health/providers-health.service.ts
  src/health/subgraphs-health.service.ts
Labels: enhancement

#933 chore: update feature request document for simplicity
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation
